<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'activite-physique',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Activité physique',
    'seo_title' => 'Auto-évaluation LifeMetrics - Activité physique',
    'description' => 'Ce questionnaire permet d\'évaluer les habitudes générales d\'activité physique d\'une personne. Il prend en compte non seulement la pratique sportive, mais également le mouvement au quotidien, le renforcement musculaire, la sédentarité et la régularité.',
    'population' => 'Adultes',
    'recall_period' => 'Principalement les 7 derniers jours ; régularité sur les 4 dernières semaines',
    'estimated_duration' => 'environ 2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'AP01',
            'dimension' => 'activite-endurance',
            'text' => 'Au cours des 7 derniers jours, combien de jours avez-vous pratiqué au moins 30 minutes d\'activité physique dynamique au total ?',
            'help' => 'Exemples : marche rapide, vélo, natation, course, fitness, travail physiquement actif ou sport.',
            'required' => true,
            'answers' => array(
                array('value' => '5_plus', 'label' => '5 jours ou plus', 'points' => 1, 'applicable' => true),
                array('value' => '4_days', 'label' => '4 jours', 'points' => 2, 'applicable' => true),
                array('value' => '2_3_days', 'label' => '2-3 jours', 'points' => 3, 'applicable' => true),
                array('value' => '1_day', 'label' => '1 jour', 'points' => 4, 'applicable' => true),
                array('value' => '0_days', 'label' => 'Aucun jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP02',
            'dimension' => 'activite-endurance',
            'text' => 'Environ combien de temps avez-vous consacré au total à une activité physique d\'intensité au moins modérée pendant les 7 derniers jours ?',
            'help' => 'Une activité d\'intensité modérée accélère la respiration tout en permettant généralement de continuer à parler.',
            'required' => true,
            'answers' => array(
                array('value' => '300_plus', 'label' => '300 minutes ou plus', 'points' => 1, 'applicable' => true),
                array('value' => '150_299', 'label' => '150 à 299 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '60_149', 'label' => '60 à 149 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '30_59', 'label' => '30 à 59 minutes', 'points' => 4, 'applicable' => true),
                array('value' => 'less_30', 'label' => 'Moins de 30 minutes', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP03',
            'dimension' => 'activite-endurance',
            'text' => 'Lorsque vous êtes physiquement actif, à quelle fréquence votre activité accélère-t-elle réellement votre respiration et votre rythme cardiaque ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque à chaque séance ou période active', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'sometimes', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP04',
            'dimension' => 'renforcement-mobilite',
            'text' => 'Au cours d\'une semaine habituelle, combien de jours réalisez-vous des activités qui sollicitent volontairement vos muscles ?',
            'help' => 'Exemples : musculation, exercices au poids du corps, élastiques, certains travaux physiques ou exercices de renforcement. Le niveau le plus favorable est atteint à partir de 2 jours par semaine.',
            'required' => true,
            'answers' => array(
                array('value' => '3_plus', 'label' => '3 jours ou plus par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2_days', 'label' => '2 jours par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '1_day', 'label' => '1 jour par semaine', 'points' => 3, 'applicable' => true),
                array('value' => 'less_1', 'label' => 'Moins d\'une fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => 'never', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP05',
            'dimension' => 'renforcement-mobilite',
            'text' => 'Vos activités physiques sollicitent-elles différentes parties du corps au cours de la semaine ?',
            'required' => true,
            'answers' => array(
                array('value' => 'whole_body', 'label' => 'Ensemble du corps de manière assez équilibrée', 'points' => 1, 'applicable' => true),
                array('value' => 'majority', 'label' => 'La majorité des grandes zones du corps', 'points' => 2, 'applicable' => true),
                array('value' => 'some_groups', 'label' => 'Quelques groupes musculaires', 'points' => 3, 'applicable' => true),
                array('value' => 'single_zone', 'label' => 'Principalement une seule zone du corps', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_none', 'label' => 'Presque aucune activité de ce type', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP06',
            'dimension' => 'mouvement-quotidien',
            'text' => 'Combien de jours par semaine utilisez-vous volontairement la marche, le vélo, les escaliers ou un autre déplacement actif dans votre quotidien ?',
            'required' => true,
            'answers' => array(
                array('value' => '6_7_days', 'label' => '6-7 jours', 'points' => 1, 'applicable' => true),
                array('value' => '4_5_days', 'label' => '4-5 jours', 'points' => 2, 'applicable' => true),
                array('value' => '2_3_days', 'label' => '2-3 jours', 'points' => 3, 'applicable' => true),
                array('value' => '1_day', 'label' => '1 jour', 'points' => 4, 'applicable' => true),
                array('value' => '0_days', 'label' => '0 jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP07',
            'dimension' => 'mouvement-quotidien',
            'text' => 'En dehors de vos séances de sport éventuelles, votre journée comporte-t-elle régulièrement des périodes où vous marchez, vous déplacez ou effectuez des tâches physiques ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_regularly', 'label' => 'Très régulièrement tout au long de la journée', 'points' => 1, 'applicable' => true),
                array('value' => 'multiple_times', 'label' => 'Plusieurs fois dans la journée', 'points' => 2, 'applicable' => true),
                array('value' => 'from_time_to_time', 'label' => 'De temps en temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP08',
            'dimension' => 'sedentarite',
            'text' => 'Lors d\'une journée habituelle, combien de temps passez-vous principalement assis ou allongé, en dehors du sommeil ?',
            'required' => true,
            'answers' => array(
                array('value' => 'less_3h', 'label' => 'Moins de 3 heures', 'points' => 1, 'applicable' => true),
                array('value' => '3_to_5h', 'label' => '3 à moins de 5 heures', 'points' => 2, 'applicable' => true),
                array('value' => '5_to_7h', 'label' => '5 à moins de 7 heures', 'points' => 3, 'applicable' => true),
                array('value' => '7_to_9h', 'label' => '7 à 9 heures', 'points' => 4, 'applicable' => true),
                array('value' => 'more_9h', 'label' => 'Plus de 9 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP09',
            'dimension' => 'sedentarite',
            'text' => 'Lorsque vous devez rester assis longtemps, à quelle fréquence vous levez-vous pour marcher ou bouger quelques minutes ?',
            'required' => true,
            'answers' => array(
                array('value' => 'every_30min', 'label' => 'Environ toutes les 30 minutes ou plus souvent', 'points' => 1, 'applicable' => true),
                array('value' => 'every_30_60min', 'label' => 'Toutes les 30 à 60 minutes', 'points' => 2, 'applicable' => true),
                array('value' => 'every_hour', 'label' => 'Environ toutes les heures', 'points' => 3, 'applicable' => true),
                array('value' => 'every_2h', 'label' => 'Environ toutes les 2 heures', 'points' => 4, 'applicable' => true),
                array('value' => 'after_2h', 'label' => 'Généralement après plus de 2 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP10',
            'dimension' => 'regularite',
            'text' => 'Votre activité physique est-elle répartie sur plusieurs jours de la semaine ?',
            'required' => true,
            'answers' => array(
                array('value' => '5_plus_days', 'label' => 'Répartie sur 5 jours ou plus', 'points' => 1, 'applicable' => true),
                array('value' => '3_4_days', 'label' => 'Répartie sur 3-4 jours', 'points' => 2, 'applicable' => true),
                array('value' => '2_days', 'label' => 'Principalement sur 2 jours', 'points' => 3, 'applicable' => true),
                array('value' => 'single_day', 'label' => 'Presque toute mon activité est concentrée sur une seule journée', 'points' => 4, 'applicable' => true),
                array('value' => 'rarely_active', 'label' => 'Je suis rarement actif', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP11',
            'dimension' => 'regularite',
            'text' => 'Au cours des 4 dernières semaines, combien de semaines ont comporté une activité physique régulière ?',
            'required' => true,
            'answers' => array(
                array('value' => '4_weeks', 'label' => 'Les 4 semaines', 'points' => 1, 'applicable' => true),
                array('value' => '3_weeks', 'label' => '3 semaines', 'points' => 2, 'applicable' => true),
                array('value' => '2_weeks', 'label' => '2 semaines', 'points' => 3, 'applicable' => true),
                array('value' => '1_week', 'label' => '1 semaine', 'points' => 4, 'applicable' => true),
                array('value' => 'none', 'label' => 'Aucune', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP12',
            'dimension' => 'regularite',
            'text' => 'Au cours d\'une semaine habituelle, combien de journées passez-vous avec très peu de marche ou d\'activité physique ?',
            'required' => true,
            'answers' => array(
                array('value' => '0_days', 'label' => 'Aucun jour ou presque', 'points' => 1, 'applicable' => true),
                array('value' => '1_2_days', 'label' => '1-2 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3_days', 'label' => '3 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4_5_days', 'label' => '4-5 jours', 'points' => 4, 'applicable' => true),
                array('value' => '6_7_days', 'label' => '6-7 jours', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'activite-endurance',
            'label' => 'Activité d\'endurance',
            'question_ids' => array('AP01', 'AP02', 'AP03'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'renforcement-mobilite',
            'label' => 'Renforcement et mobilité',
            'question_ids' => array('AP04', 'AP05'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'mouvement-quotidien',
            'label' => 'Mouvement au quotidien',
            'question_ids' => array('AP06', 'AP07'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'sedentarite',
            'label' => 'Sédentarité',
            'question_ids' => array('AP08', 'AP09'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'regularite',
            'label' => 'Régularité',
            'question_ids' => array('AP10', 'AP11', 'AP12'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'SATISFAISANTE',
            'rank' => 0,
            'min' => 12,
            'max' => 24,
            'title' => 'Activité physique satisfaisante',
            'description' => 'Votre niveau d\'activité physique est satisfaisant. D\'après vos réponses, vos habitudes d\'activité physique sont globalement favorables. Vous semblez maintenir un niveau d\'activité régulier et suffisamment présent dans votre quotidien. Votre résultat indique que plusieurs dimensions évaluées - activité dynamique, mouvement quotidien, renforcement musculaire, gestion de la sédentarité et régularité - sont bien intégrées à vos habitudes. Certaines dimensions peuvent néanmoins rester perfectibles. L\'objectif est principalement de maintenir vos bonnes habitudes dans la durée et de conserver un équilibre entre activité physique, mouvement quotidien et récupération.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'A_RENFORCER',
            'rank' => 1,
            'min' => 25,
            'max' => 32,
            'title' => 'Activité physique à renforcer',
            'description' => 'Votre niveau d\'activité physique est à renforcer. D\'après vos réponses, vous avez déjà certaines habitudes favorables, mais votre niveau global d\'activité physique peut encore être amélioré. Vous pouvez être actif dans certaines situations ou pratiquer régulièrement une activité physique, tout en conservant des points faibles dans d\'autres dimensions : volume d\'activité, mouvement au quotidien, renforcement musculaire, temps passé assis ou régularité. Votre priorité est d\'identifier les dimensions qui limitent actuellement votre score et de renforcer progressivement ces habitudes afin d\'obtenir un profil plus équilibré.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'INSUFFISANTE',
            'rank' => 2,
            'min' => 33,
            'max' => 60,
            'title' => 'Activité physique insuffisante',
            'description' => 'Votre niveau d\'activité physique est insuffisant. D\'après vos réponses, plusieurs dimensions de votre activité physique semblent actuellement insuffisantes. Votre résultat peut notamment refléter un volume d\'activité trop faible, un manque de mouvement au quotidien, une pratique de renforcement insuffisante, des périodes prolongées en position assise ou un manque de régularité. Il est important d\'agir progressivement sur les dimensions les moins favorables de votre profil. Augmenter le mouvement quotidien, interrompre plus régulièrement les périodes assises et intégrer davantage d\'activité physique au cours de la semaine constituent des axes d\'amélioration possibles.',
            'recommendations' => array(),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(),
    'safety_messages' => array(),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir mon bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Le Score LifeMetrics - Activité physique est un outil d\'auto-évaluation informatif. Il ne constitue pas un diagnostic médical et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le questionnaire ne mesure pas directement la condition physique, la masse musculaire, la composition corporelle ou l\'état de santé. Les résultats du questionnaire ne doivent pas être utilisés pour déduire directement une mesure VitaScan ou une donnée corporelle.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => true,
        'technical_runtime' => true,
        'publication' => true,
    ),
);
