<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'activite-physique',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Activité physique',
    'seo_title' => 'Auto-évaluation LifeMetrics - Quel est votre niveau d\'activité physique ?',
    'description' => 'Évaluer le profil global d\'activité physique : volume d\'activité, renforcement musculaire, mouvement quotidien, réduction de la sédentarité et régularité.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => 'Principalement les 7 derniers jours ; régularité sur les 4 dernières semaines',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'AP01',
            'dimension' => 'activite-endurance',
            'text' => 'Au cours des 7 derniers jours, combien de jours avez-vous pratiqué au moins 30 minutes d\'activité physique dynamique au total ?',
            'help' => 'Exemples : marche rapide, vélo, natation, course, fitness, travail physiquement actif ou sport.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Aucun jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2-3 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '4 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '5 jours ou plus', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP02',
            'dimension' => 'activite-endurance',
            'text' => 'Environ combien de temps avez-vous consacré au total à une activité physique d\'intensité au moins modérée pendant les 7 derniers jours ?',
            'help' => 'Une activité d\'intensité modérée accélère la respiration, tout en permettant généralement de continuer à parler.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Moins de 30 minutes', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '30 à 59 minutes', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '60 à 149 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '150 à 299 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '300 minutes ou plus', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP03',
            'dimension' => 'activite-endurance',
            'text' => 'Lorsque vous êtes physiquement actif, à quelle fréquence votre activité accélère-t-elle réellement votre respiration et votre rythme cardiaque ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque à chaque séance ou période active', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP04',
            'dimension' => 'renforcement-mobilite',
            'text' => 'Au cours d\'une semaine habituelle, combien de jours réalisez-vous des activités qui sollicitent volontairement vos muscles ?',
            'help' => 'Exemples : musculation, exercices au poids du corps, élastiques, certains travaux physiques ou exercices de renforcement.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins d\'une fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1 jour par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2 jours par semaine', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => '3 jours ou plus par semaine', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP05',
            'dimension' => 'renforcement-mobilite',
            'text' => 'Vos activités physiques sollicitent-elles différentes parties du corps au cours de la semaine ?',
            'help' => 'Par exemple : jambes, dos, tronc, épaules et bras.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque aucune activité de ce type', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Principalement une seule zone du corps', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Quelques groupes musculaires', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'La majorité des grandes zones du corps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Ensemble du corps de manière assez équilibrée', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP06',
            'dimension' => 'mouvement-quotidien',
            'text' => 'Combien de jours par semaine utilisez-vous volontairement la marche, le vélo, les escaliers ou un autre déplacement actif dans votre quotidien ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => '0 jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2-3 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '4-5 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '6-7 jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP07',
            'dimension' => 'mouvement-quotidien',
            'text' => 'En dehors de vos séances de sport éventuelles, votre journée comporte-t-elle régulièrement des périodes où vous marchez, vous déplacez ou effectuez des tâches physiques ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'De temps en temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Plusieurs fois dans la journée', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulièrement tout au long de la journée', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP08',
            'dimension' => 'sedentarite',
            'text' => 'Lors d\'une journée habituelle, combien de temps passez-vous principalement assis ou allongé, en dehors du sommeil ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 9 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '7 à 9 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '5 à moins de 7 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '3 à moins de 5 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Moins de 3 heures', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP09',
            'dimension' => 'sedentarite',
            'text' => 'Lorsque vous devez rester assis longtemps, à quelle fréquence vous levez-vous pour marcher ou bouger quelques minutes ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Généralement après plus de 2 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Environ toutes les 2 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ toutes les heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Toutes les 30 à 60 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Environ toutes les 30 minutes ou plus souvent', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP10',
            'dimension' => 'regularite',
            'text' => 'Votre activité physique est-elle répartie sur plusieurs jours de la semaine ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Je suis rarement actif', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Presque toute mon activité est concentrée sur une seule journée', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Principalement sur 2 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Répartie sur 3-4 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Répartie sur 5 jours ou plus', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP11',
            'dimension' => 'regularite',
            'text' => 'Au cours des 4 dernières semaines, combien de semaines ont comporté une activité physique régulière ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Aucune', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2 semaines', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '3 semaines', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Les 4 semaines', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'AP12',
            'dimension' => 'regularite',
            'text' => 'Au cours d\'une semaine habituelle, combien de journées passez-vous avec très peu de marche ou d\'activité physique ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => '6-7 jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '4-5 jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '3 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-2 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Aucun jour ou presque', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'activite-endurance',
            'label' => 'Activité d\'endurance',
            'question_ids' => array('AP01', 'AP02', 'AP03'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'renforcement-mobilite',
            'label' => 'Renforcement et mobilité',
            'question_ids' => array('AP04', 'AP05'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'mouvement-quotidien',
            'label' => 'Mouvement au quotidien',
            'question_ids' => array('AP06', 'AP07'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'sedentarite',
            'label' => 'Sédentarité',
            'question_ids' => array('AP08', 'AP09'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'regularite',
            'label' => 'Régularité',
            'question_ids' => array('AP10', 'AP11', 'AP12'),
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'ACTIVITE_INSUFFISANTE',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Activité insuffisante',
            'description' => 'Votre niveau d\'activité physique semble actuellement faible. Votre quotidien comporte probablement peu d\'activité dynamique, des périodes prolongées de sédentarité ou une activité trop irrégulière. Même une augmentation progressive de votre niveau d\'activité peut être bénéfique. Commencez par des changements accessibles : marcher davantage, utiliser les escaliers, interrompre régulièrement les périodes assises ou ajouter quelques périodes d\'activité dans la semaine.',
            'recommendations' => array(
                'Augmenter progressivement le mouvement quotidien',
                'Réduire les longues périodes passées assis',
                'Introduire des activités d\'endurance accessibles',
                'Ajouter progressivement du renforcement musculaire',
            ),
        ),
        array(
            'code' => 'ACTIVITE_A_RENFORCER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Activité à renforcer',
            'description' => 'Vous êtes déjà actif dans certaines situations, mais votre activité reste probablement insuffisante ou irrégulière sur plusieurs dimensions. Vous disposez d\'une bonne base pour progresser. Identifiez les éléments qui limitent votre score afin de cibler quelques changements simples.',
            'recommendations' => array(
                'Durée totale d\'activité',
                'Régularité',
                'Renforcement musculaire',
                'Mouvement quotidien',
                'Temps passé assis',
            ),
        ),
        array(
            'code' => 'NIVEAU_FAVORABLE',
            'rank' => 2,
            'min' => 28,
            'max' => 39,
            'title' => 'Niveau favorable',
            'description' => 'Votre mode de vie comporte un niveau d\'activité globalement favorable. Vous combinez probablement plusieurs formes de mouvement et votre activité se rapproche des principaux repères recommandés pour les adultes.',
            'recommendations' => array(
                'Maintenir une activité régulière',
                'Combiner endurance et renforcement',
                'Conserver du mouvement dans le quotidien',
                'Interrompre régulièrement les périodes assises',
            ),
        ),
        array(
            'code' => 'TRES_BON_NIVEAU',
            'rank' => 3,
            'min' => 40,
            'max' => 48,
            'title' => 'Très bon niveau d\'activité',
            'description' => 'Votre profil indique des habitudes particulièrement favorables en matière d\'activité physique. Votre activité semble régulière, diversifiée et bien intégrée à votre quotidien, avec relativement peu de comportements très sédentaires. L\'enjeu principal n\'est pas nécessairement de « faire toujours plus », mais de maintenir ces habitudes dans la durée et de conserver un bon équilibre entre activité, récupération et contraintes personnelles.',
            'recommendations' => array(
                'Maintenir ces habitudes dans la durée',
                'Conserver un bon équilibre entre activité, récupération et contraintes personnelles',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(),
    'safety_messages' => array(),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir le bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est un outil informatif destiné à vous aider à mieux comprendre vos habitudes d\'activité physique. Elle ne constitue pas un diagnostic médical et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Activité physique est un indicateur propriétaire d\'auto-évaluation. Ses catégories ne constituent pas des seuils diagnostiques ou cliniques. En présence d\'une maladie, d\'une limitation fonctionnelle ou lors d\'une reprise d\'activité après une longue interruption, il peut être approprié de discuter de l\'activité physique adaptée avec un professionnel de santé.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
