<?php

return array(
    "schema_version" => "2.0.0",
    "id" => "risque-nutritionnel",
    "version" => "1.0.0",
    "status" => "review",
    "locale" => "fr-FR",
    "title" => "Score LifeMetrics - Risque nutritionnel",
    "seo_title" => "Auto-évaluation LifeMetrics - Risque nutritionnel",
    "description" => "Évaluer les signes déclarés de vulnérabilité nutritionnelle : baisse de l'appétit, réduction des apports, évolution pondérale involontaire, difficultés à s'alimenter ou obstacles compromettant la continuité des repas.",
    "population" => "Adultes de 18 à 64 ans",
    "recall_period" => "4 dernières semaines (RN05 : 3 derniers mois)",
    "estimated_duration" => "2-3 minutes",
    "scoring_direction" => "lower_is_better",
    "score" => array(
        "target_min" => 12,
        "target_max" => 60,
        "normalize_when_unavailable" => false,
        "rounding" => "half_up",
    ),
    "questions" => array(
        array(
            "id" => "RN01",
            "dimension" => "appetit-satiete",
            "text" => "Au cours des 4 dernières semaines, comment décririez-vous votre appétit par rapport à votre niveau habituel ?",
            "help" => "Cette question mesure l'envie de manger, indépendamment de la quantité réellement consommée.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Mon appétit est habituel ou très bon", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Il est légèrement diminué", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Il est modérément diminué", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Il est nettement diminué", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Il est très faible ou presque absent", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN02",
            "dimension" => "appetit-satiete",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence vous êtes-vous senti rassasié très rapidement, au point de ne pas pouvoir terminer un repas que vous auriez normalement mangé ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque tous les jours", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN03",
            "dimension" => "reduction-apports-alimentaires",
            "text" => "Au cours des 4 dernières semaines, par rapport à vos habitudes, quelle quantité avez-vous généralement consommée lors de vos repas ?",
            "help" => "La question évalue une diminution réelle des apports par rapport aux habitudes de la personne.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Mes quantités habituelles", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Un peu moins que d'habitude", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Environ les trois quarts de mes quantités habituelles", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Environ la moitié de mes quantités habituelles", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Nettement moins de la moitié de mes quantités habituelles", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN04",
            "dimension" => "reduction-apports-alimentaires",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence avez-vous sauté un repas principal ou mangé seulement une très petite quantité alors que vous auriez normalement pris un repas complet ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Moins d'une fois par semaine", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "1 à 2 jours par semaine", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "3 à 4 jours par semaine", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "5 jours par semaine ou plus", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN05",
            "dimension" => "evolution-ponderale-involontaire",
            "text" => "Au cours des 3 derniers mois, avez-vous constaté une perte de poids sans avoir cherché volontairement à maigrir ?",
            "help" => "Cette question utilise volontairement une période de 3 mois. Elle repose sur l'évolution déclarée par l'utilisateur et ne remplace pas une mesure professionnelle du poids.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Non, aucune perte de poids constatée", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Peut-être une légère baisse, difficile à confirmer", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Oui, une baisse légère mais clairement perceptible", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Oui, une baisse importante", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Oui, une baisse très importante ou rapide", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN06",
            "dimension" => "evolution-ponderale-involontaire",
            "text" => "Au cours des dernières semaines, dans quelle mesure avez-vous remarqué, sans l'avoir recherché, des signes comme des vêtements devenus plus amples ou le besoin de resserrer davantage votre ceinture ?",
            "help" => "Il s'agit d'un indicateur déclaratif complémentaire et non d'une mesure de composition corporelle.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Pas du tout", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Très légèrement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Modérément", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Nettement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très nettement", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN07",
            "dimension" => "difficultes-alimenter",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence des difficultés à mâcher vous ont-elles conduit à manger moins ou à éviter certains aliments ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque tous les jours", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN08",
            "dimension" => "difficultes-alimenter",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence avez-vous eu des difficultés à avaler des aliments ou des boissons ?",
            "help" => "Une difficulté importante à avaler est également prise en compte dans le bloc de sécurité, indépendamment du score numérique.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque tous les jours", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN09",
            "dimension" => "symptomes-limitant-alimentation",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence des symptômes comme des nausées, vomissements, douleurs ou inconforts digestifs vous ont-ils conduit à manger moins que prévu ?",
            "help" => "La question mesure uniquement l'impact des symptômes sur l'alimentation et ne cherche pas à en identifier la cause.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque tous les jours", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN10",
            "dimension" => "symptomes-limitant-alimentation",
            "text" => "Au cours des 4 dernières semaines, quelle a été la plus longue période pendant laquelle des symptômes ou un problème de santé vous ont conduit à manger nettement moins que d'habitude ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Aucune période de ce type", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Environ 1 jour", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "2 à 3 jours consécutifs", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "4 à 6 jours consécutifs", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "7 jours consécutifs ou davantage", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN11",
            "dimension" => "acces-autonomie-continuite-repas",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence des difficultés à faire les courses, à vous déplacer ou à accéder aux aliments dont vous aviez besoin vous ont-elles conduit à manger moins que prévu ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très souvent", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "RN12",
            "dimension" => "acces-autonomie-continuite-repas",
            "text" => "Au cours des 4 dernières semaines, à quelle fréquence des difficultés à préparer ou organiser vos repas vous ont-elles conduit à prendre un repas insuffisant ou à ne pas manger ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Jamais ou presque jamais", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Rarement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Parfois", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Souvent", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très souvent", "points" => 5, "applicable" => true),
            ),
        ),
    ),
    "dimensions" => array(
        array(
            "id" => "appetit-satiete",
            "label" => "Appétit et satiété",
            "question_ids" => array("RN01", "RN02"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "reduction-apports-alimentaires",
            "label" => "Réduction des apports alimentaires",
            "question_ids" => array("RN03", "RN04"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "evolution-ponderale-involontaire",
            "label" => "Évolution pondérale involontaire",
            "question_ids" => array("RN05", "RN06"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "difficultes-alimenter",
            "label" => "Difficultés à s'alimenter",
            "question_ids" => array("RN07", "RN08"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "symptomes-limitant-alimentation",
            "label" => "Symptômes limitant l'alimentation",
            "question_ids" => array("RN09", "RN10"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "acces-autonomie-continuite-repas",
            "label" => "Accès, autonomie et continuité des repas",
            "question_ids" => array("RN11", "RN12"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
    ),
    "weakest_dimensions" => array(
        "count" => 2,
        "tie_break" => "configuration_order",
    ),
    "result_levels" => array(
        array(
            "code" => "RISQUE_FAIBLE",
            "rank" => 1,
            "min" => 12,
            "max" => 24,
            "title" => "Risque nutritionnel faible",
            "description" => "Votre risque nutritionnel déclaré est actuellement faible. D'après vos réponses, vous présentez actuellement peu de signes de vulnérabilité nutritionnelle parmi les situations évaluées. Votre appétit, vos apports alimentaires, votre capacité à maintenir vos repas et votre alimentation au quotidien apparaissent globalement préservés. Ce résultat indique un profil favorable dans le cadre de cette auto-évaluation, sans permettre pour autant de conclure sur votre état nutritionnel complet.",
            "recommendations" => array(
                "Maintenir une alimentation régulière et équilibrée",
                "Rester attentif à l'apparition d'une baisse persistante de l'appétit, des apports ou du poids",
            ),
        ),
        array(
            "code" => "RISQUE_A_SURVEILLER",
            "rank" => 2,
            "min" => 25,
            "max" => 32,
            "title" => "Risque nutritionnel à surveiller",
            "description" => "Votre situation nutritionnelle mérite une surveillance particulière. Vos réponses font apparaître plusieurs signes pouvant fragiliser votre alimentation. Il peut s'agir d'une diminution de l'appétit, de quantités consommées plus faibles, de repas moins réguliers, d'une évolution involontaire du poids ou de difficultés qui compliquent l'alimentation. Ces éléments ne permettent pas de poser un diagnostic, mais ils sont suffisamment présents pour justifier une attention particulière.",
            "recommendations" => array(
                "Identifier les dimensions les moins favorables et surveiller leur évolution",
                "Demander conseil à un pharmacien ou à un professionnel de santé si les difficultés persistent ou s'aggravent",
            ),
        ),
        array(
            "code" => "RISQUE_IMPORTANT",
            "rank" => 3,
            "min" => 33,
            "max" => 60,
            "title" => "Risque nutritionnel important",
            "description" => "Votre risque nutritionnel est actuellement important. Vos réponses montrent plusieurs difficultés importantes concernant l'alimentation, les apports ou leur maintien dans le temps. Le résultat peut notamment refléter une diminution marquée de l'appétit, des quantités consommées insuffisantes par rapport à vos habitudes, une perte de poids involontaire, des difficultés à manger ou des symptômes limitant régulièrement l'alimentation. Plusieurs dimensions contribuent donc actuellement à un profil nutritionnel défavorable.",
            "recommendations" => array(
                "Ne pas s'appuyer uniquement sur cette auto-évaluation",
                "Un échange avec un pharmacien ou un professionnel de santé est recommandé afin d'évaluer plus précisément la situation",
            ),
        ),
    ),
    "classification_rules" => array(
        array(
            "id" => "RN_GUARDRAIL_RN03",
            "type" => "category_cap",
            "metric" => "question_score",
            "question_id" => "RN03",
            "operator" => ">=",
            "value" => 4,
            "max_category" => "RISQUE_A_SURVEILLER",
            "message_code" => "RN_GUARDRAIL_APPORT_REDUIT",
        ),
        array(
            "id" => "RN_GUARDRAIL_RN04",
            "type" => "category_cap",
            "metric" => "question_score",
            "question_id" => "RN04",
            "operator" => ">=",
            "value" => 4,
            "max_category" => "RISQUE_A_SURVEILLER",
            "message_code" => "RN_GUARDRAIL_REPAS_SAUTES",
        ),
        array(
            "id" => "RN_GUARDRAIL_RN05",
            "type" => "category_cap",
            "metric" => "question_score",
            "question_id" => "RN05",
            "operator" => ">=",
            "value" => 4,
            "max_category" => "RISQUE_A_SURVEILLER",
            "message_code" => "RN_GUARDRAIL_PERTE_POIDS",
        ),
        array(
            "id" => "RN_GUARDRAIL_RN08",
            "type" => "category_cap",
            "metric" => "question_score",
            "question_id" => "RN08",
            "operator" => ">=",
            "value" => 4,
            "max_category" => "RISQUE_A_SURVEILLER",
            "message_code" => "RN_GUARDRAIL_DEGLUTITION",
        ),
    ),
    "classification_messages" => array(
        "RN_GUARDRAIL_APPORT_REDUIT" => array(
            "title" => "Point de vigilance : Réduction des quantités consommées",
            "text" => "Une diminution importante de vos quantités consommées a été déclarée et nécessite une surveillance particulière.",
        ),
        "RN_GUARDRAIL_REPAS_SAUTES" => array(
            "title" => "Point de vigilance : Repas fréquemment sautés ou fortement réduits",
            "text" => "Le fait de sauter fréquemment des repas ou de manger de très petites quantités fragilise vos apports nutritionnels.",
        ),
        "RN_GUARDRAIL_PERTE_POIDS" => array(
            "title" => "Point de vigilance : Perte de poids involontaire",
            "text" => "Une perte de poids involontaire importante a été déclarée au cours des derniers mois.",
        ),
        "RN_GUARDRAIL_DEGLUTITION" => array(
            "title" => "Point de vigilance : Difficultés de déglutition",
            "text" => "Des difficultés fréquentes à avaler des aliments ou des boissons ont été déclarées et justifient un avis médical.",
        ),
    ),
    "improvement_messages" => array(
        "appetit-satiete" => array(
            "title" => "Appétit et satiété",
            "text" => "Votre appétit ou votre sensation de satiété précoce peuvent contribuer à réduire vos prises alimentaires. Veillez à fractionner vos repas si nécessaire.",
        ),
        "reduction-apports-alimentaires" => array(
            "title" => "Réduction des apports alimentaires",
            "text" => "Vos quantités consommées ou la régularité de vos repas principaux sont diminuées. Maintenez des repas complets et réguliers.",
        ),
        "evolution-ponderale-involontaire" => array(
            "title" => "Évolution pondérale involontaire",
            "text" => "Une perte de poids non souhaitée ou des changements corporels ont été remarqués. Surveillez régulièrement votre poids.",
        ),
        "difficultes-alimenter" => array(
            "title" => "Difficultés à s'alimenter",
            "text" => "Des difficultés de mastication ou de déglutition compliquent votre alimentation. Adaptez la texture des aliments et demandez conseil.",
        ),
        "symptomes-limitant-alimentation" => array(
            "title" => "Symptômes limitant l'alimentation",
            "text" => "Des nausées, douleurs ou inconforts digestifs limitent vos prises alimentaires. Parlez-en à un professionnel de santé.",
        ),
        "acces-autonomie-continuite-repas" => array(
            "title" => "Accès, autonomie et continuité des repas",
            "text" => "L'accès aux courses ou la préparation des repas constituent un obstacle à une alimentation suffisante. Explorez les aides disponibles.",
        ),
    ),
    "safety_questions" => array(
        array(
            "id" => "RNSF01",
            "text" => "Avez-vous récemment constaté une perte de poids importante ou rapide sans avoir cherché à maigrir ?",
            "help" => "Une perte de poids involontaire rapide constitue un signal d'alerte nutritionnel.",
            "required" => true,
            "answers" => array(
                array("value" => "no", "label" => "Non", "triggers" => array()),
                array("value" => "yes", "label" => "Oui", "triggers" => array("RN_SAFETY_MESSAGE")),
            ),
        ),
        array(
            "id" => "RNSF02",
            "text" => "Depuis plusieurs jours, mangez-vous très peu ou avez-vous des difficultés importantes à vous alimenter suffisamment ?",
            "help" => "Une réduction drastique des apports sur plusieurs jours justifie un avis rapide.",
            "required" => true,
            "answers" => array(
                array("value" => "no", "label" => "Non", "triggers" => array()),
                array("value" => "yes", "label" => "Oui", "triggers" => array("RN_SAFETY_MESSAGE")),
            ),
        ),
        array(
            "id" => "RNSF03",
            "text" => "Avez-vous actuellement des difficultés importantes à avaler, des épisodes d'étouffement pendant les repas ou l'impression que les aliments passent difficilement ?",
            "help" => "Les fausses routes ou blocages alimentaires nécessitent une évaluation médicale.",
            "required" => true,
            "answers" => array(
                array("value" => "no", "label" => "Non", "triggers" => array()),
                array("value" => "yes", "label" => "Oui", "triggers" => array("RN_SAFETY_MESSAGE")),
            ),
        ),
        array(
            "id" => "RNSF04",
            "text" => "Des symptômes tels que des vomissements répétés, des douleurs importantes ou un autre problème de santé vous empêchent-ils actuellement de vous alimenter normalement ?",
            "help" => "Des symptômes aigus bloquant l'alimentation justifient un conseil professionnel.",
            "required" => true,
            "answers" => array(
                array("value" => "no", "label" => "Non", "triggers" => array()),
                array("value" => "yes", "label" => "Oui", "triggers" => array("RN_SAFETY_MESSAGE")),
            ),
        ),
    ),
    "safety_messages" => array(
        "RN_SAFETY_MESSAGE" => array(
            "priority" => 100,
            "title" => "Un point mérite votre attention.",
            "text" => "Une perte de poids involontaire importante, une forte diminution des apports ou des difficultés à vous alimenter normalement justifient de demander conseil à un professionnel de santé.",
        ),
    ),
    "result_ctas" => array(
        array(
            "label" => "Je veux faire un bilan",
            "url" => "https://lifemetrics.fr/formulaire-bilan/",
            "variant" => "primary",
            "enabled" => true,
        ),
        array(
            "label" => "Découvrir les autres questionnaires",
            "url" => "/tests-sante/",
            "variant" => "secondary",
            "enabled" => true,
        ),
    ),
    "funnel" => array(
        "title" => "Pour compléter votre évaluation",
        "text" => "Ce questionnaire évalue des signes déclarés pouvant fragiliser votre alimentation. Il ne mesure pas directement votre état nutritionnel ni votre composition corporelle. Si votre résultat nécessite une surveillance, vous pouvez en parler avec un pharmacien ou un professionnel de santé. Dans les pharmacies équipées, VitaScan peut également fournir plusieurs mesures corporelles complémentaires dans le cadre d'un bilan. Ces mesures apportent des informations supplémentaires, mais elles ne couvrent pas à elles seules l'ensemble de l'état nutritionnel et ne permettent pas de diagnostiquer une dénutrition ou d'en déterminer la cause.",
        "partner_cta_label" => "Trouver une pharmacie équipée de VitaScan",
    ),
    "disclaimer" => array(
        "before" => "Cette auto-évaluation LifeMetrics est destinée à repérer des signes déclarés de vulnérabilité nutritionnelle.",
        "after" => "Le Score LifeMetrics - Risque nutritionnel est un outil propriétaire d'auto-évaluation destiné à repérer des signes déclarés de vulnérabilité nutritionnelle. Il ne constitue pas un diagnostic médical et ne remplace pas l'évaluation d'un médecin, d'un diététicien ou d'un autre professionnel de santé. Les catégories proposées sont des niveaux d'orientation LifeMetrics et ne constituent pas des seuils diagnostiques ou cliniques.",
    ),
    "disclaimers" => array(
        "general" => "Le Score LifeMetrics - Risque nutritionnel est un outil propriétaire d'auto-évaluation destiné à repérer des signes déclarés de vulnérabilité nutritionnelle. Il ne constitue pas un diagnostic médical et ne remplace pas l'évaluation d'un médecin, d'un diététicien ou d'un autre professionnel de santé. Les catégories proposées sont des niveaux d'orientation LifeMetrics et ne constituent pas des seuils diagnostiques ou cliniques.",
        "scientific" => "Le questionnaire repose principalement sur les réponses et perceptions déclarées par l'utilisateur. Il ne mesure pas directement les apports énergétiques ou protéiques, les carences nutritionnelles, la masse musculaire, la force musculaire ou l'ensemble de la composition corporelle. Il ne permet pas de confirmer ou d'exclure une dénutrition, une sarcopénie, une carence ou une autre pathologie. Une personne peut présenter un poids ou un IMC apparemment normal tout en nécessitant une évaluation nutritionnelle plus approfondie.",
        "partner" => "Les informations obtenues avec VitaScan sont complémentaires et ne doivent pas être utilisées seules pour confirmer ou exclure un risque nutritionnel.",
    ),
    "approvals" => array(
        "content_scoring" => true,
        "legal_licensing" => false,
        "technical_runtime" => true,
        "publication" => false,
    ),
);
