<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'nutrition',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Nutrition',
    'seo_title' => 'Auto-évaluation LifeMetrics - Comment évaluer la qualité globale de votre alimentation ?',
    'description' => 'Évaluer la qualité générale des habitudes alimentaires : diversité végétale, fibres, protéines, qualité des graisses, produits à limiter et organisation alimentaire.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => 'Habitudes habituelles des 14 derniers jours',
    'estimated_duration' => 'Environ 3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'NT01',
            'dimension' => 'fruits-legumes-diversite',
            'text' => 'Au cours des 14 derniers jours, combien de portions de fruits et légumes avez-vous consommées en moyenne chaque jour ?',
            'help' => 'Exemple d\'une portion : un fruit de taille moyenne, une petite assiette de légumes ou une portion adaptée de légumes cuits.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Moins de 1 portion par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 à 2 portions', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ 3 portions', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ 4 portions', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '5 portions ou plus', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT02',
            'dimension' => 'fruits-legumes-diversite',
            'text' => 'Au cours d\'une semaine habituelle, votre alimentation comprend-elle une variété de fruits, légumes et autres aliments d\'origine végétale ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très peu variée', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Peu variée', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Moyennement variée', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Assez variée', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très variée', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT03',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Au cours d\'une semaine habituelle, à quelle fréquence consommez-vous des légumes secs ?',
            'help' => 'Exemples : lentilles, pois chiches, haricots secs, pois cassés.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins d\'une fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ 1 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2 fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => '3 fois ou plus par semaine', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT04',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Lorsque vous consommez du pain, du riz, des pâtes, de la semoule ou d\'autres produits céréaliers, à quelle fréquence choisissez-vous une version complète ou semi-complète ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT05',
            'dimension' => 'proteines-variete',
            'text' => 'Au cours d\'une semaine habituelle, alternez-vous différentes sources de protéines ?',
            'help' => 'Exemples : poisson, oeufs, volaille, légumes secs, produits laitiers, viande, tofu ou autres alternatives adaptées.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque toujours la même source', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Très peu de variété', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Quelques sources différentes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Plusieurs sources régulièrement alternées', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Grande variété, incluant régulièrement des sources végétales', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT06',
            'dimension' => 'proteines-variete',
            'text' => 'Au cours d\'une semaine habituelle, à quelle fréquence consommez-vous du poisson ou, si vous n\'en mangez pas, des alternatives permettant de diversifier vos sources de protéines et de bonnes graisses ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins d\'une fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ 1 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ 2 fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => 'Plus de 2 fois par semaine avec une bonne variété', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT07',
            'dimension' => 'matieres-grasses-qualite',
            'text' => 'Pour cuisiner ou assaisonner vos repas, à quelle fréquence privilégiez-vous des huiles végétales comme l\'huile d\'olive, de colza ou de noix plutôt que des matières grasses riches en graisses saturées ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT08',
            'dimension' => 'matieres-grasses-qualite',
            'text' => 'Au cours des 14 derniers jours, quelle place les aliments frais ou peu transformés et les repas préparés simplement ont-ils occupée dans votre alimentation ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très faible', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Faible', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié de mon alimentation', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Importante', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très importante', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT09',
            'dimension' => 'produits-a-limiter',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous consommé des boissons sucrées ?',
            'help' => 'Exemples : sodas, boissons énergisantes, thés glacés sucrés, sirops et autres boissons contenant des sucres ajoutés.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Environ 1 fois par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '4-6 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-3 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement ou jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT10',
            'dimension' => 'produits-a-limiter',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence les produits très gras, très sucrés, très salés ou ultra-transformés ont-ils occupé une place importante dans vos repas ou collations ?',
            'help' => 'Exemples : certains snacks, biscuits, pâtisseries, produits frits, plats préparés ou fast-foods.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Environ tous les jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '4-6 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-3 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT11',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vos repas principaux combinaient-ils plusieurs groupes d\'aliments complémentaires ?',
            'help' => 'Exemples : légumes ou fruits + source de protéines + source de glucides adaptée ou autre accompagnement varié.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié des repas', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT12',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre organisation alimentaire vous a-t-elle permis de manger de façon relativement régulière sans grignotages fréquents ou repas improvisés faute d\'organisation ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'fruits-legumes-diversite',
            'label' => 'Fruits, légumes et diversité végétale',
            'question_ids' => array('NT01', 'NT02'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'fibres-glucides-qualite',
            'label' => 'Fibres et glucides de qualité',
            'question_ids' => array('NT03', 'NT04'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'proteines-variete',
            'label' => 'Protéines et variété alimentaire',
            'question_ids' => array('NT05', 'NT06'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'matieres-grasses-qualite',
            'label' => 'Matières grasses et qualité des aliments',
            'question_ids' => array('NT07', 'NT08'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'produits-a-limiter',
            'label' => 'Produits à limiter',
            'question_ids' => array('NT09', 'NT10'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'organisation-equilibre-global',
            'label' => 'Organisation et équilibre global',
            'question_ids' => array('NT11', 'NT12'),
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_A_AMELIORER',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Habitudes alimentaires à améliorer',
            'description' => 'Vos réponses suggèrent que plusieurs dimensions de votre alimentation peuvent actuellement être améliorées. Votre alimentation peut manquer de variété ou comporter trop peu d\'aliments végétaux et riches en fibres, tandis que certains produits à limiter peuvent occuper une place importante.',
            'recommendations' => array(
                'Augmenter progressivement les fruits et légumes',
                'Intégrer davantage de légumes secs',
                'Choisir plus souvent des céréales complètes',
                'Diversifier les sources de protéines',
                'Réduire progressivement les boissons sucrées et produits très transformés',
            ),
        ),
        array(
            'code' => 'EQUILIBRE_A_RENFORCER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Équilibre nutritionnel à renforcer',
            'description' => 'Votre alimentation comporte déjà certaines habitudes favorables, mais plusieurs dimensions pourraient encore être renforcées. Repérez les catégories dans lesquelles votre score est le plus faible et choisissez en priorité un ou deux axes d\'amélioration.',
            'recommendations' => array(
                'Végétaux',
                'Fibres',
                'Variété protéique',
                'Qualité des matières grasses',
                'Produits à limiter',
                'Organisation alimentaire',
            ),
        ),
        array(
            'code' => 'PROFIL_GLOBALEMENT_FAVORABLE',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Profil alimentaire globalement favorable',
            'description' => 'Vos réponses décrivent une alimentation globalement variée et équilibrée. Vous semblez intégrer régulièrement plusieurs des principaux repères nutritionnels : aliments végétaux, sources de fibres, diversification des protéines et limitation raisonnable de certains produits.',
            'recommendations' => array(
                'Maintenir la diversité',
                'Conserver une place importante aux aliments peu transformés',
                'Varier les sources de protéines',
                'Continuer à limiter les boissons sucrées et produits ultra-transformés',
                'Travailler les dimensions encore légèrement plus faibles',
            ),
        ),
        array(
            'code' => 'HABITUDES_TRES_FAVORABLES',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Habitudes alimentaires très favorables',
            'description' => 'Votre profil indique des habitudes alimentaires particulièrement favorables sur les dimensions évaluées. Votre alimentation semble diversifiée, riche en aliments végétaux et relativement peu dépendante des produits très transformés.',
            'recommendations' => array(
                'Maintenir ces habitudes sur le long terme',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'NTSF01',
            'text' => 'Suivez-vous actuellement un régime alimentaire spécifique pour une raison médicale ?',
            'help' => 'Exemples : diabète, maladie rénale, allergie, maladie digestive ou maladie métabolique.',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'NTSF02',
            'text' => 'Avez-vous perdu ou pris une quantité importante de poids récemment sans l\'avoir réellement souhaité ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'NTSF03',
            'text' => 'Avez-vous actuellement des difficultés importantes à vous alimenter ou des préoccupations concernant votre comportement alimentaire ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'NUTRITION_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Votre situation peut nécessiter des conseils plus personnalisés.',
            'text' => 'Cette auto-évaluation générale ne tient pas compte de certaines situations médicales ou nutritionnelles particulières. Si nécessaire, parlez-en à un médecin ou à un professionnel de la nutrition.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir le bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre certaines de vos habitudes alimentaires. Elle ne constitue pas une évaluation nutritionnelle médicale, ne permet pas de diagnostiquer une carence ou une maladie et ne remplace pas les conseils d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Nutrition est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories sont conçus à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques. Les besoins nutritionnels peuvent varier en fonction notamment de l\'âge, de l\'activité physique, de l\'état de santé et de situations particulières.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
