<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'nutrition',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Nutrition',
    'seo_title' => 'Auto-évaluation LifeMetrics - Nutrition',
    'description' => 'Le Score LifeMetrics - Nutrition est une auto-évaluation destinée à aider une personne à mieux comprendre la qualité générale de ses habitudes alimentaires.',
    'population' => 'Adultes',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => 'environ 3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'NT01',
            'dimension' => 'fruits-legumes-diversite-vegetale',
            'text' => 'Au cours des 14 derniers jours, combien de portions de fruits et légumes avez-vous consommées en moyenne chaque jour ?',
            'required' => true,
            'answers' => array(
                array('value' => '5_portions_or_more', 'label' => '5 portions ou plus', 'points' => 1, 'applicable' => true),
                array('value' => 'about_4_portions', 'label' => 'Environ 4 portions', 'points' => 2, 'applicable' => true),
                array('value' => 'about_3_portions', 'label' => 'Environ 3 portions', 'points' => 3, 'applicable' => true),
                array('value' => '1_to_2_portions', 'label' => '1 à 2 portions', 'points' => 4, 'applicable' => true),
                array('value' => 'less_1_portion_per_day', 'label' => 'Moins de 1 portion par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT02',
            'dimension' => 'fruits-legumes-diversite-vegetale',
            'text' => 'Au cours d\'une semaine habituelle, votre alimentation comprend-elle une variété de fruits, légumes et autres aliments d\'origine végétale ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_varied', 'label' => 'Très variée', 'points' => 1, 'applicable' => true),
                array('value' => 'fairly_varied', 'label' => 'Assez variée', 'points' => 2, 'applicable' => true),
                array('value' => 'moderately_varied', 'label' => 'Moyennement variée', 'points' => 3, 'applicable' => true),
                array('value' => 'little_varied', 'label' => 'Peu variée', 'points' => 4, 'applicable' => true),
                array('value' => 'very_little_varied', 'label' => 'Très peu variée', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT03',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Au cours d\'une semaine habituelle, à quelle fréquence consommez-vous des légumes secs ?',
            'help' => 'Exemples : lentilles, pois chiches, haricots secs, pois cassés.',
            'required' => true,
            'answers' => array(
                array('value' => '3_or_more_week', 'label' => '3 fois ou plus par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2_week', 'label' => '2 fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => 'about_1_week', 'label' => 'Environ 1 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => 'less_1_week', 'label' => 'Moins d\'une fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT04',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Lorsque vous consommez du pain, du riz, des pâtes, de la semoule ou d\'autres produits céréaliers, à quelle fréquence choisissez-vous une version complète ou semi-complète ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT05',
            'dimension' => 'proteines-variete-alimentaire',
            'text' => 'Au cours d\'une semaine habituelle, alternez-vous différentes sources de protéines ?',
            'required' => true,
            'answers' => array(
                array('value' => 'great_variety', 'label' => 'Grande variété, incluant régulièrement des sources végétales', 'points' => 1, 'applicable' => true),
                array('value' => 'several_sources', 'label' => 'Plusieurs sources régulièrement alternées', 'points' => 2, 'applicable' => true),
                array('value' => 'few_sources', 'label' => 'Quelques sources différentes', 'points' => 3, 'applicable' => true),
                array('value' => 'very_little_variety', 'label' => 'Très peu de variété', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_always_same', 'label' => 'Presque toujours la même source', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT06',
            'dimension' => 'proteines-variete-alimentaire',
            'text' => 'Au cours d\'une semaine habituelle, à quelle fréquence consommez-vous du poisson ou, si vous n\'en mangez pas, des alternatives permettant de diversifier vos sources de protéines et de bonnes graisses ?',
            'required' => true,
            'answers' => array(
                array('value' => 'more_2_week', 'label' => 'Plus de 2 fois par semaine avec une bonne variété', 'points' => 1, 'applicable' => true),
                array('value' => 'about_2_week', 'label' => 'Environ 2 fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => 'about_1_week', 'label' => 'Environ 1 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => 'less_1_week', 'label' => 'Moins d\'une fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => 'never', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT07',
            'dimension' => 'matieres-grasses-qualite-aliments',
            'text' => 'Pour cuisiner ou assaisonner vos repas, à quelle fréquence privilégiez-vous des huiles végétales comme l\'huile d\'olive, de colza ou de noix plutôt que des matières grasses riches en graisses saturées ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT08',
            'dimension' => 'matieres-grasses-qualite-aliments',
            'text' => 'Au cours des 14 derniers jours, quelle place les aliments frais ou peu transformés et les repas préparés simplement ont-ils occupée dans votre alimentation ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_important', 'label' => 'Très importante', 'points' => 1, 'applicable' => true),
                array('value' => 'important', 'label' => 'Importante', 'points' => 2, 'applicable' => true),
                array('value' => 'half_diet', 'label' => 'Environ la moitié de mon alimentation', 'points' => 3, 'applicable' => true),
                array('value' => 'low', 'label' => 'Faible', 'points' => 4, 'applicable' => true),
                array('value' => 'very_low', 'label' => 'Très faible', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT09',
            'dimension' => 'produits-a-limiter',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous consommé des boissons sucrées ?',
            'required' => true,
            'answers' => array(
                array('value' => 'rarely_never', 'label' => 'Rarement ou jamais', 'points' => 1, 'applicable' => true),
                array('value' => '1_3_week', 'label' => '1-3 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '4_6_week', 'label' => '4-6 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => 'about_1_day', 'label' => 'Environ 1 fois par jour', 'points' => 4, 'applicable' => true),
                array('value' => 'several_day', 'label' => 'Plusieurs fois par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT10',
            'dimension' => 'produits-a-limiter',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence les produits très gras, très sucrés, très salés ou ultra-transformés ont-ils occupé une place importante dans vos repas ou collations ?',
            'required' => true,
            'answers' => array(
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '1_3_week', 'label' => '1-3 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '4_6_week', 'label' => '4-6 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => 'about_every_day', 'label' => 'Environ tous les jours', 'points' => 4, 'applicable' => true),
                array('value' => 'several_day', 'label' => 'Plusieurs fois par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT11',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vos repas principaux combinaient-ils plusieurs groupes d\'aliments complémentaires ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_meals', 'label' => 'Environ la moitié des repas', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT12',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre organisation alimentaire vous a-t-elle permis de manger de façon relativement régulière sans grignotages fréquents ou repas improvisés faute d\'organisation ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'fruits-legumes-diversite-vegetale',
            'label' => 'Fruits, légumes et diversité végétale',
            'question_ids' => array('NT01', 'NT02'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'fibres-glucides-qualite',
            'label' => 'Fibres et glucides de qualité',
            'question_ids' => array('NT03', 'NT04'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'proteines-variete-alimentaire',
            'label' => 'Protéines et variété alimentaire',
            'question_ids' => array('NT05', 'NT06'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'matieres-grasses-qualite-aliments',
            'label' => 'Matières grasses et qualité des aliments',
            'question_ids' => array('NT07', 'NT08'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'produits-a-limiter',
            'label' => 'Produits à limiter',
            'question_ids' => array('NT09', 'NT10'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'organisation-equilibre-global',
            'label' => 'Organisation et équilibre global',
            'question_ids' => array('NT11', 'NT12'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_FAVORABLES',
            'rank' => 0,
            'min' => 12,
            'max' => 24,
            'title' => 'Habitudes alimentaires globalement favorables',
            'description' => 'Vos habitudes alimentaires sont globalement favorables. D\'après vos réponses, votre alimentation présente un profil globalement favorable sur plusieurs dimensions évaluées. La place des végétaux, des fibres, la variété des sources de protéines, la qualité des aliments, la limitation de certains produits et l\'organisation générale de vos repas semblent globalement bien intégrées à vos habitudes. Certaines dimensions peuvent néanmoins rester perfectibles. L\'objectif principal est de maintenir les habitudes favorables dans le temps et de conserver un profil alimentaire suffisamment diversifié et équilibré.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'EQUILIBRE_FRAGILE',
            'rank' => 1,
            'min' => 25,
            'max' => 32,
            'title' => 'Équilibre alimentaire encore fragile',
            'description' => 'Votre équilibre alimentaire reste encore fragile. D\'après vos réponses, votre alimentation comporte plusieurs habitudes favorables, mais votre profil n\'est pas encore suffisamment homogène pour être considéré comme globalement satisfaisant. Certaines dimensions restent à renforcer. Il peut s\'agir de la diversité végétale, de la consommation de fibres, de la variété des sources de protéines, de la qualité des aliments, de la fréquence des produits à limiter ou de l\'organisation des repas. Votre profil se situe dans une zone intermédiaire : de bonnes bases sont présentes, mais plusieurs habitudes continuent de limiter l\'équilibre global de votre alimentation.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'HABITUDES_INSUFFISANTES',
            'rank' => 2,
            'min' => 33,
            'max' => 60,
            'title' => 'Habitudes alimentaires insuffisantes',
            'description' => 'Vos habitudes alimentaires nécessitent actuellement des améliorations importantes. D\'après vos réponses, plusieurs de vos habitudes alimentaires ne sont actuellement pas suffisamment favorables. Votre alimentation peut notamment comporter trop peu de fruits, légumes, légumes secs ou produits riches en fibres, manquer de diversité, accorder une place importante aux boissons sucrées ou aux produits très transformés, ou présenter une organisation des repas insuffisamment régulière. Plusieurs dimensions contribuent donc actuellement à un profil alimentaire défavorable.',
            'recommendations' => array(),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'NTSF01',
            'text' => 'Suivez-vous actuellement un régime alimentaire spécifique pour une raison médicale ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'NTSF02',
            'text' => 'Avez-vous perdu ou pris une quantité importante de poids récemment sans l\'avoir réellement souhaité ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'NTSF03',
            'text' => 'Avez-vous actuellement des difficultés importantes à vous alimenter ou des préoccupations concernant votre comportement alimentaire ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
    ),
    'safety_messages' => array(
        'NUTRITION_SAFETY_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Un point mérite votre attention.',
            'text' => 'Certaines situations médicales, variations de poids importantes ou difficultés à vous alimenter peuvent nécessiter des conseils personnalisés d’un professionnel de santé ou de la nutrition.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Le Score LifeMetrics - Nutrition est un outil propriétaire d\'auto-évaluation destiné à fournir un repère informatif sur certaines habitudes alimentaires. Il ne constitue pas une évaluation nutritionnelle médicale, ne permet pas de diagnostiquer une carence ou une maladie et ne remplace pas les conseils d\'un professionnel de santé.',
        'after' => 'Le score et les catégories ne constituent pas des seuils diagnostiques ou cliniques. Le questionnaire repose sur les habitudes alimentaires déclarées par l\'utilisateur. Il ne permet pas de déterminer les besoins énergétiques individuels, la consommation calorique réelle, la présence d\'une carence ou la cause d\'une prise ou d\'une perte de poids. Il ne permet pas non plus de déduire directement la composition corporelle ou le métabolisme de l\'utilisateur. En présence d\'un régime médical spécifique, d\'une variation pondérale involontaire importante ou de difficultés importantes concernant l\'alimentation, des conseils plus personnalisés peuvent être nécessaires.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => true,
        'technical_runtime' => true,
        'publication' => true,
    ),
);
