<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'nutrition',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Nutrition',
    'seo_title' => 'Auto-évaluation LifeMetrics - Comment évaluer la qualité globale de votre alimentation ?',
    'description' => 'Évaluer le profil global des habitudes alimentaires : diversité végétale, qualité des glucides et fibres, variété des sources protéiques, matières grasses, produits à limiter et organisation des repas.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '7 derniers jours',
    'estimated_duration' => '3-4 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'NT01',
            'dimension' => 'fruits-legumes-diversite',
            'text' => 'Au cours des 7 derniers jours, combien de portions de légumes avez-vous consommées en moyenne par jour ?',
            'help' => 'Une portion correspond environ à une poignée, un petit bol de soupe, une demi-assiette de légumes cuits ou une belle salade.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Moins de 1 portion par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 portion par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2 portions par jour', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '3 portions par jour', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '4 portions ou plus par jour', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT02',
            'dimension' => 'fruits-legumes-diversite',
            'text' => 'Au cours des 7 derniers jours, combien de portions de fruits frais avez-vous consommées en moyenne par jour ?',
            'help' => 'Une portion correspond environ à un fruit entier de taille moyenne (pomme, poire, banane) ou à une poignée de petits fruits.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Rarement ou jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins de 1 fruit par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1 fruit par jour', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2 fruits par jour', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => '3 fruits ou plus par jour', 'points' => 3, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT03',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Au cours des 7 derniers jours, à quelle fréquence avez-vous consommé des légumes secs (lentilles, pois chiches, haricots secs, fèves...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins d\'une fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2 fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => '3 fois ou plus par semaine', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT04',
            'dimension' => 'fibres-glucides-qualite',
            'text' => 'Lorsque vous consommez du pain, des pâtes, du riz ou d\'autres céréales, à quelle fréquence choisissez-vous des versions complètes ou semi-complètes ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Rarement ou jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'De temps en temps', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'La plupart du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT05',
            'dimension' => 'proteines-variete',
            'text' => 'Au cours de la semaine, vos repas principaux comportent-ils des sources variées de protéines (œufs, poissons, volailles, viandes, légumes secs, tofu...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très peu variées, toujours les mêmes aliments', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Peu variées', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Moyennement variées', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Assez variées', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très variées selon les jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT06',
            'dimension' => 'proteines-variete',
            'text' => 'À quelle fréquence consommez-vous du poisson ou des alternatives riches en oméga-3 (poissons gras, huiles adaptées, graines...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Rarement ou jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Moins d\'une fois par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ 1 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ 2 fois par semaine', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => 'Plus de 2 fois par semaine ou sources quotidiennes adaptées', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT07',
            'dimension' => 'matieres-grasses-qualite',
            'text' => 'Quelles matières grasses utilisez-vous le plus souvent pour assaisonner ou cuisiner au quotidien ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Principalement beurre en grande quantité, margarine dure ou sauces industrielles grasses', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Mélange variable avec souvent des graisses saturées', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Huiles végétales courantes sans attention particulière', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Principalement huile d\'olive, de colza ou de noix', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Huiles végétales de qualité variées (olive, colza, noix) adaptées aux usages', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT08',
            'dimension' => 'matieres-grasses-qualite',
            'text' => 'Consommez-vous régulièrement des oléagineux non salés (noix, noisettes, amandes...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Rarement ou jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 à 2 fois par mois', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1 à 2 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '3 à 4 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Une petite poignée presque tous les jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT09',
            'dimension' => 'produits-a-limiter',
            'text' => 'À quelle fréquence consommez-vous des boissons sucrées (sodas, jus industriels, thés glacés sucrés, boissons énergisantes...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 fois par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '3 à 5 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1 à 2 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement ou jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT10',
            'dimension' => 'produits-a-limiter',
            'text' => 'À quelle fréquence consommez-vous des produits très transformés gras, sucrés ou salés (biscuits, viennoiseries, snacks, plats préparés industriels...) ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Au moins 1 fois par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '4 à 6 fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2 à 3 fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement (1 fois par semaine ou moins)', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT11',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'À quelle fréquence préparez-vous vous-même vos repas à partir d\'ingrédients bruts ou peu transformés ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Rarement ou jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '1 à 2 jours par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '3 à 4 jours par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '5 à 6 jours par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Tous les jours ou presque', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'NT12',
            'dimension' => 'organisation-equilibre-global',
            'text' => 'Comment décririez-vous le rythme et la régularité de vos repas au cours de la semaine ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très anarchique, nombreux sauts de repas non choisis ou grignotages continus', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent irrégulier', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Assez régulier en semaine mais très déstructuré le week-end', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Régulier la plupart du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Bien structuré et adapté à votre rythme de vie', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'fruits-legumes-diversite',
            'label' => 'Fruits, légumes et diversité végétale',
            'question_ids' => array('NT01', 'NT02'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'fibres-glucides-qualite',
            'label' => 'Fibres et qualité des glucides',
            'question_ids' => array('NT03', 'NT04'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'proteines-variete',
            'label' => 'Sources de protéines et variété',
            'question_ids' => array('NT05', 'NT06'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'matieres-grasses-qualite',
            'label' => 'Qualité des matières grasses',
            'question_ids' => array('NT07', 'NT08'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'produits-a-limiter',
            'label' => 'Produits sucrés, ultra-transformés et boissons sucrées',
            'question_ids' => array('NT09', 'NT10'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'organisation-equilibre-global',
            'label' => 'Fait maison, rythme et structure des repas',
            'question_ids' => array('NT11', 'NT12'),
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_A_AMELIORER',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Habitudes nutritionnelles à améliorer',
            'description' => 'Vos réponses indiquent que plusieurs dimensions fondamentales de votre alimentation sont actuellement peu favorables. Vous consommez probablement peu de végétaux, peu de fibres, ou une proportion importante de produits ultra-transformés ou sucrés.',
            'recommendations' => array(
                'Augmenter progressivement la place des légumes et des fruits',
                'Introduire des féculents complets et des légumes secs dans la semaine',
                'Réduire les boissons sucrées et les snacks ultra-transformés',
                'Cuisiner plus souvent des aliments bruts simples',
            ),
        ),
        array(
            'code' => 'EQUILIBRE_A_RENFORCER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Équilibre nutritionnel à renforcer',
            'description' => 'Votre alimentation comporte déjà certains points positifs, mais plusieurs leviers essentiels peuvent être consolidés. Il peut s\'agir de la régularité de la consommation végétale, de la qualité des matières grasses ou de la réduction des produits transformés.',
            'recommendations' => array(
                'Maintenir vos habitudes déjà favorables',
                'Cibler vos 2 dimensions les plus faibles',
                'Privilégier les huiles de qualité (olive, colza, noix) et les oléagineux',
                'Structurer davantage vos repas pour limiter les grignotages',
            ),
        ),
        array(
            'code' => 'PROFIL_GLOBALEMENT_FAVORABLE',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Profil nutritionnel globalement favorable',
            'description' => 'Vos habitudes alimentaires présentent une structure globalement favorable : place satisfaisante des végétaux, qualité globale des aliments choisis et limitation relative des produits ultra-transformés.',
            'recommendations' => array(
                'Conserver la régularité de vos choix actuels',
                'Continuer à varier les sources de protéines et de végétaux',
                'Optimiser les détails qui peuvent encore être améliorés',
            ),
        ),
        array(
            'code' => 'HABITUDES_TRES_FAVORABLES',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Habitudes nutritionnelles très favorables',
            'description' => 'Vos réponses décrivent un profil nutritionnel très favorable. Vos apports semblent riches en végétaux, diversifiés, de bonne qualité globale et bien structurés au quotidien.',
            'recommendations' => array(
                'Conserver ces excellentes habitudes sur le long terme',
                'Adapter vos apports selon vos périodes d\'activité ou vos besoins spécifiques',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'NTSF01',
            'text' => 'Suivez-vous un régime alimentaire médicalement prescrit (diabète, maladie rénale, maladie cardiovasculaire sévère, maladie cœliaque...) ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'NTSF02',
            'text' => 'Avez-vous constaté une perte ou une prise de poids involontaire importante au cours des derniers mois ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'NTSF03',
            'text' => 'Avez-vous des difficultés importantes à vous alimenter (perte totale d\'appétit, douleurs digestives sévères, troubles sévères du comportement alimentaire) ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('NUTRITION_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'NUTRITION_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses méritent une attention particulière.',
            'text' => 'Cette auto-évaluation fournit un aperçu de vos habitudes générales. Elle ne se substitue pas à une prise en charge médicale ou diététique individualisée.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir le bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics a pour objectif de vous aider à faire le point sur vos habitudes alimentaires récentes. Elle ne constitue pas un diagnostic médical ni une prescription diététique individualisée.',
        'after' => 'Le Score LifeMetrics - Nutrition est un indicateur propriétaire d\'auto-évaluation conçu à des fins d\'information et de sensibilisation. Il ne remplace pas une consultation médicale ni un suivi par un diététicien-nutritionniste. En présence d\'une pathologie chronique, de troubles digestifs sévères ou de troubles du comportement alimentaire, consultez un professionnel de santé.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
