<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'hydratation',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Hydratation',
    'seo_title' => 'Auto-évaluation LifeMetrics - Vos habitudes d\'hydratation sont-elles adaptées ?',
    'description' => 'Le Score LifeMetrics - Hydratation est une auto-évaluation destinée à aider une personne à mieux comprendre la qualité et la régularité de ses habitudes quotidiennes d\'hydratation.',
    'population' => 'Adultes',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => true,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'HY01',
            'dimension' => 'eau-boissons-quotidiennes',
            'text' => 'Au cours des 14 derniers jours, quelle place l\'eau a-t-elle occupée parmi les boissons que vous consommez pour vous hydrater ?',
            'help' => 'L\'eau peut être plate ou gazeuse.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'L\'eau est clairement ma boisson principale', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Majoritaire', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié de mes boissons', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Faible', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très faible', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY02',
            'dimension' => 'eau-boissons-quotidiennes',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu l\'impression de boire suffisamment pour vos besoins au cours de la journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque tous les jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY03',
            'dimension' => 'repartition-hydratation',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous bu régulièrement à différents moments de la journée plutôt que de boire une grande quantité seulement à quelques occasions ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY04',
            'dimension' => 'repartition-hydratation',
            'text' => 'Au cours d\'une journée habituelle, à quelle fréquence passez-vous plusieurs heures sans rien boire simplement parce que vous êtes occupé, que vous oubliez ou que vous n\'avez rien à proximité ?',
            'help' => 'Plus les longues périodes sans boire sont fréquentes, plus le score est défavorable.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très souvent', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY05',
            'dimension' => 'adaptation-activite-chaleur',
            'text' => 'Lorsque vous pratiquez une activité physique ou effectuez un effort prolongé, adaptez-vous votre hydratation avant, pendant ou après l\'activité selon sa durée, son intensité et les conditions ?',
            'help' => '« Non concerné actuellement » reste hors score et ne reçoit aucun point.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
                array('value' => 'na', 'label' => 'Non concerné actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'HY06',
            'dimension' => 'adaptation-activite-chaleur',
            'text' => 'Lorsqu\'il fait chaud ou que vous transpirez davantage que d\'habitude, pensez-vous à augmenter ou à rendre plus régulière votre consommation d\'eau ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY07',
            'dimension' => 'choix-boissons',
            'text' => 'Lorsque vous avez soif, à quelle fréquence choisissez-vous en priorité de l\'eau ou une boisson non sucrée adaptée plutôt qu\'une boisson très sucrée ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY08',
            'dimension' => 'choix-boissons',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence les sodas, boissons énergisantes, boissons sucrées ou sirops ont-ils constitué une part importante de vos boissons quotidiennes ?',
            'help' => 'Plus les boissons sucrées occupent une place importante, plus le score est défavorable.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Rarement ou jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1-3 jours par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '4-6 jours par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Environ tous les jours', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Plusieurs fois par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY09',
            'dimension' => 'alimentation-environnement',
            'text' => 'Votre alimentation comprend-elle régulièrement des aliments riches en eau, par exemple des fruits, des légumes, des soupes, des laitages ou d\'autres aliments comparables ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Tous les jours ou presque', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'De temps en temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY10',
            'dimension' => 'alimentation-environnement',
            'text' => 'Dans votre quotidien, avez-vous généralement de l\'eau facilement disponible lorsque vous travaillez, étudiez, vous déplacez ou restez longtemps à l\'extérieur de chez vous ?',
            'help' => 'Exemples : bouteille, gourde, carafe, fontaine ou accès facile à un point d\'eau.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY11',
            'dimension' => 'anticipation-regularite',
            'text' => 'Lorsque vous prévoyez une longue journée, un déplacement, un voyage, du sport ou plusieurs heures loin de chez vous, pensez-vous à prévoir l\'accès à de l\'eau ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY12',
            'dimension' => 'anticipation-regularite',
            'text' => 'Au cours des 14 derniers jours, vos bonnes habitudes d\'hydratation ont-elles été relativement régulières, y compris pendant les journées de travail, d\'études ou les week-ends ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très régulières', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Généralement régulières', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Variables selon les jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Plutôt irrégulières', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très irrégulières', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'eau-boissons-quotidiennes',
            'label' => 'Eau et boissons quotidiennes',
            'question_ids' => array('HY01', 'HY02'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'repartition-hydratation',
            'label' => 'Répartition de l\'hydratation',
            'question_ids' => array('HY03', 'HY04'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'adaptation-activite-chaleur',
            'label' => 'Adaptation activité / chaleur',
            'question_ids' => array('HY05', 'HY06'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'choix-boissons',
            'label' => 'Choix des boissons',
            'question_ids' => array('HY07', 'HY08'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'alimentation-environnement',
            'label' => 'Alimentation et environnement',
            'question_ids' => array('HY09', 'HY10'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'anticipation-regularite',
            'label' => 'Anticipation et régularité',
            'question_ids' => array('HY11', 'HY12'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_FAVORABLES',
            'rank' => 0,
            'min' => 12,
            'max' => 24,
            'title' => 'Habitudes d\'hydratation globalement favorables',
            'description' => 'Vos habitudes d\'hydratation sont globalement favorables. D\'après vos réponses, vos habitudes d\'hydratation apparaissent globalement favorables dans plusieurs dimensions évaluées. L\'eau occupe une place importante dans vos boissons, votre hydratation semble relativement bien répartie au cours de la journée et vos habitudes sont généralement régulières. Vous semblez également anticiper suffisamment l\'accès à l\'eau et adapter vos habitudes aux différentes situations qui vous concernent. Certaines dimensions peuvent néanmoins rester perfectibles. L\'objectif principal est de maintenir ces habitudes dans le temps et de conserver une hydratation régulière et adaptée à votre quotidien.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'HYDRATATION_FRAGILE',
            'rank' => 1,
            'min' => 25,
            'max' => 32,
            'title' => 'Hydratation encore fragile',
            'description' => 'Vos habitudes d\'hydratation restent encore fragiles. D\'après vos réponses, vous disposez déjà de plusieurs habitudes favorables, mais votre profil n\'est pas encore suffisamment régulier ou homogène pour être considéré comme globalement satisfaisant. Certaines situations peuvent encore poser problème : longues périodes sans boire, journées chargées, déplacements, disponibilité de l\'eau, choix des boissons, chaleur ou activité physique lorsque cela vous concerne. Votre profil se situe dans une zone intermédiaire : plusieurs bonnes habitudes sont présentes, mais certaines faiblesses restent suffisamment importantes pour limiter la qualité globale de votre hydratation au quotidien.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'HABITUDES_INSUFFISANTES',
            'rank' => 2,
            'min' => 33,
            'max' => 60,
            'title' => 'Habitudes d\'hydratation insuffisantes',
            'description' => 'Vos habitudes d\'hydratation sont actuellement insuffisantes. D\'après vos réponses, plusieurs de vos habitudes d\'hydratation ne sont actuellement pas suffisamment favorables. Vous pouvez notamment boire de manière trop irrégulière, passer de longues périodes sans boire, peu anticiper vos besoins ou ne pas suffisamment adapter votre comportement à la chaleur et aux efforts. Le choix de vos boissons, la place de l\'eau ou son accessibilité au cours de la journée peuvent également contribuer à un profil défavorable. Plusieurs dimensions nécessitent donc actuellement une attention particulière.',
            'recommendations' => array(),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'HYSF01',
            'text' => 'Un professionnel de santé vous a-t-il demandé de limiter, contrôler ou adapter précisément votre consommation de liquides ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATATION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'HYSF02',
            'text' => 'Avez-vous actuellement ou récemment eu des pertes importantes de liquides, par exemple en raison de vomissements, diarrhées, fièvre ou transpiration inhabituelle ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATATION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'HYSF03',
            'text' => 'Avez-vous actuellement des symptômes importants tels qu\'une faiblesse inhabituelle, des vertiges marqués, une confusion, un malaise ou une diminution inhabituelle des urines ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATATION_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
    ),
    'safety_messages' => array(
        'HYDRATATION_SAFETY_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses nécessitent une attention particulière.',
            'text' => 'Cette auto-évaluation ne permet pas d\'évaluer votre état d\'hydratation ni de déterminer la quantité de liquide adaptée à une situation médicale particulière. En cas de symptômes importants, de pertes importantes de liquides ou si un professionnel de santé vous a donné des consignes spécifiques, suivez ces recommandations et demandez conseil à un professionnel de santé si nécessaire. Un résultat favorable ne doit jamais masquer un message d\'attention déclenché par une question de sécurité.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Le Score LifeMetrics - Hydratation est un outil propriétaire d\'auto-évaluation destiné à fournir un repère informatif sur les habitudes quotidiennes d\'hydratation. Il ne mesure pas directement l\'état physiologique d\'hydratation, ne permet pas de diagnostiquer une déshydratation et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le score et les catégories ne constituent pas des seuils diagnostiques ou cliniques. Le questionnaire repose sur les habitudes déclarées par l\'utilisateur. Il ne détermine pas une quantité universelle d\'eau à boire et ne permet pas de calculer précisément les besoins hydriques individuels. Les besoins peuvent varier selon notamment l\'alimentation, l\'activité physique, la température, l\'état de santé et différentes situations individuelles. Le questionnaire ne permet pas de conclure directement sur l\'état physiologique d\'hydratation. En présence de symptômes importants, de pertes importantes de liquides ou de recommandations médicales spécifiques concernant les boissons, l\'avis d\'un professionnel de santé reste prioritaire.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => true,
        'technical_runtime' => true,
        'publication' => true,
    ),
);

