<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'hydratation',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Hydratation',
    'seo_title' => 'Auto-évaluation LifeMetrics - Vos habitudes d\'hydratation sont-elles adaptées ?',
    'description' => 'Évaluez vos habitudes quotidiennes d\'hydratation : régularité, place de l\'eau, répartition, adaptation à l\'activité et à la chaleur, choix des boissons et anticipation.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => true,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'HY01',
            'dimension' => 'place-eau',
            'text' => 'Au cours des 14 derniers jours, quelle place l\'eau a-t-elle occupée parmi les boissons que vous consommez pour vous hydrater ?',
            'help' => 'L\'eau peut être plate ou gazeuse.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très faible', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Faible', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié de mes boissons', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Majoritaire', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'L\'eau est clairement ma boisson principale', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY02',
            'dimension' => 'place-eau',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu l\'impression de boire suffisamment pour vos besoins au cours de la journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque tous les jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY03',
            'dimension' => 'repartition-hydratation',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous bu régulièrement à différents moments de la journée plutôt que de boire une grande quantité seulement à quelques occasions ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY04',
            'dimension' => 'repartition-hydratation',
            'text' => 'Au cours d\'une journée habituelle, à quelle fréquence passez-vous plusieurs heures sans rien boire simplement parce que vous êtes occupé, que vous oubliez ou que vous n\'avez rien à proximité ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très souvent', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY05',
            'dimension' => 'adaptation-activite-chaleur',
            'text' => 'Lorsque vous pratiquez une activité physique ou effectuez un effort prolongé, adaptez-vous votre hydratation avant, pendant ou après l\'activité selon sa durée, son intensité et les conditions ?',
            'help' => 'Si aucune activité physique significative n\'est pratiquée actuellement, l\'interface peut proposer « Non concerné actuellement ».',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
                array('value' => 'na', 'label' => 'Non concerné actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'HY06',
            'dimension' => 'adaptation-activite-chaleur',
            'text' => 'Lorsqu\'il fait chaud ou que vous transpirez davantage que d\'habitude, pensez-vous à augmenter ou à rendre plus régulière votre consommation d\'eau ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY07',
            'dimension' => 'choix-boissons',
            'text' => 'Lorsque vous avez soif, à quelle fréquence choisissez-vous en priorité de l\'eau ou une boisson non sucrée adaptée plutôt qu\'une boisson très sucrée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY08',
            'dimension' => 'choix-boissons',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence les sodas, boissons énergisantes, boissons sucrées ou sirops ont-ils constitué une part importante de vos boissons quotidiennes ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Environ tous les jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '4-6 jours par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-3 jours par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement ou jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY09',
            'dimension' => 'alimentation-environnement',
            'text' => 'Votre alimentation comprend-elle régulièrement des aliments riches en eau, par exemple des fruits, des légumes, des soupes, des laitages ou d\'autres aliments comparables ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'De temps en temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Tous les jours ou presque', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY10',
            'dimension' => 'alimentation-environnement',
            'text' => 'Dans votre quotidien, avez-vous généralement de l\'eau facilement disponible lorsque vous travaillez, étudiez, vous déplacez ou restez longtemps à l\'extérieur de chez vous ?',
            'help' => 'Exemples : bouteille, gourde, carafe, fontaine ou accès facile à un point d\'eau.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY11',
            'dimension' => 'anticipation-regularite',
            'text' => 'Lorsque vous prévoyez une longue journée, un déplacement, un voyage, du sport ou plusieurs heures loin de chez vous, pensez-vous à prévoir l\'accès à de l\'eau ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'HY12',
            'dimension' => 'anticipation-regularite',
            'text' => 'Au cours des 14 derniers jours, vos bonnes habitudes d\'hydratation ont-elles été relativement régulières, y compris pendant les journées de travail, d\'études ou les week-ends ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très irrégulières', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Plutôt irrégulières', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Variables selon les jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement régulières', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulières', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'place-eau',
            'label' => 'Place de l\'eau',
            'question_ids' => array('HY01', 'HY02'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'repartition-hydratation',
            'label' => 'Répartition de l\'hydratation',
            'question_ids' => array('HY03', 'HY04'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'adaptation-activite-chaleur',
            'label' => 'Adaptation à l\'activité et à la chaleur',
            'question_ids' => array('HY05', 'HY06'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'choix-boissons',
            'label' => 'Choix des boissons',
            'question_ids' => array('HY07', 'HY08'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'alimentation-environnement',
            'label' => 'Alimentation et environnement',
            'question_ids' => array('HY09', 'HY10'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'anticipation-regularite',
            'label' => 'Anticipation et régularité',
            'question_ids' => array('HY11', 'HY12'),
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_HYDRATATION_INSUFFISANTES',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Habitudes d\'hydratation insuffisantes',
            'description' => 'Vos réponses suggèrent que plusieurs de vos habitudes d\'hydratation peuvent actuellement être améliorées. Vous pouvez notamment boire de manière trop irrégulière, oublier de boire pendant de longues périodes, peu adapter votre hydratation à l\'effort ou à la chaleur, ou laisser d\'autres boissons prendre une place importante par rapport à l\'eau.',
            'recommendations' => array(
                'Rendre l\'eau facilement disponible',
                'Boire plus régulièrement au cours de la journée',
                'Éviter les longues périodes d\'oubli',
                'Adapter votre hydratation lors de la chaleur et de l\'activité physique',
                'Privilégier plus souvent l\'eau comme boisson principale',
            ),
        ),
        array(
            'code' => 'HYDRATATION_A_RENFORCER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Hydratation à renforcer',
            'description' => 'Vous disposez déjà de certaines habitudes favorables, mais votre hydratation semble encore irrégulière dans plusieurs situations. Quelques adaptations pratiques peuvent suffire à améliorer nettement votre profil.',
            'recommendations' => array(
                'Répartition des boissons dans la journée',
                'Disponibilité de l\'eau',
                'Adaptation aux efforts',
                'Adaptation à la chaleur',
                'Choix des boissons',
                'Régularité',
            ),
        ),
        array(
            'code' => 'HABITUDES_HYDRATATION_FAVORABLES',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Habitudes d\'hydratation favorables',
            'description' => 'Vos réponses décrivent des habitudes d\'hydratation globalement favorables. Vous semblez boire de manière relativement régulière, utiliser fréquemment l\'eau comme boisson principale et adapter votre comportement à une partie de vos besoins quotidiens.',
            'recommendations' => array(
                'Conserver une bonne disponibilité de l\'eau',
                'Continuer à répartir votre hydratation au cours de la journée',
                'Adapter davantage les apports en période chaude ou lors des efforts',
                'Maintenir une alimentation variée contribuant également à l\'apport hydrique',
            ),
        ),
        array(
            'code' => 'TRES_BONNES_HABITUDES_HYDRATATION',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Très bonnes habitudes d\'hydratation',
            'description' => 'Votre profil indique des habitudes d\'hydratation particulièrement favorables sur les dimensions évaluées. Vous semblez intégrer l\'hydratation de manière régulière dans votre quotidien et adapter votre comportement aux principales situations susceptibles d\'augmenter vos besoins.',
            'recommendations' => array(
                'Maintenir ces habitudes. Il n\'est pas nécessaire de chercher à boire toujours davantage pour obtenir le meilleur score.',
                'Les besoins en eau sont variables et un score élevé ne signifie pas qu\'une quantité illimitée d\'eau serait bénéfique.',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'HYSF01',
            'text' => 'Un professionnel de santé vous a-t-il demandé de limiter, contrôler ou adapter précisément votre consommation de liquides ?',
            'help' => 'Certaines situations médicales peuvent nécessiter des consignes spécifiques.',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'HYSF02',
            'text' => 'Avez-vous actuellement ou récemment eu des pertes importantes de liquides, par exemple en raison de vomissements, diarrhées, fièvre ou transpiration inhabituelle ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATION_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'HYSF03',
            'text' => 'Avez-vous actuellement des symptômes importants tels qu\'une faiblesse inhabituelle, des vertiges marqués, une confusion, un malaise ou une diminution inhabituelle des urines ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HYDRATION_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'HYDRATION_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses nécessitent une attention particulière.',
            'text' => 'Cette auto-évaluation générale ne permet pas d\'évaluer votre état d\'hydratation ni de déterminer la quantité de liquide adaptée à une situation médicale particulière. En cas de symptômes importants, de pertes importantes de liquides ou si un professionnel de santé vous a donné des consignes spécifiques, suivez ces recommandations et demandez conseil à un professionnel de santé si nécessaire.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir mon bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre vos habitudes d\'hydratation. Elle ne mesure pas directement votre état d\'hydratation, ne permet pas de diagnostiquer une déshydratation et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Hydratation est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories sont conçus à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques. Les besoins hydriques varient notamment selon l\'âge, le sexe, l\'alimentation, l\'activité physique, la température, l\'état de santé et certaines situations physiologiques ou médicales.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
