<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'fatigue-recuperation',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Fatigue & récupération',
    'seo_title' => 'Auto-évaluation LifeMetrics - Comment récupérez-vous au quotidien ?',
    'description' => 'Évaluer le profil de fatigue ressentie et la capacité de récupération au quotidien, sans rechercher une cause médicale.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'FR01',
            'dimension' => 'energie-recuperation-reveil',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous réveillé avec suffisamment d\'énergie pour commencer votre journée ?',
            'help' => 'Mesure l\'énergie disponible au démarrage de la journée, sans remplacer le questionnaire Sommeil.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque tous les jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR02',
            'dimension' => 'energie-recuperation-reveil',
            'text' => 'Après une nuit de sommeil ou une période normale de repos, à quelle fréquence avez-vous eu l\'impression d\'avoir réellement récupéré ?',
            'help' => 'Mesure le caractère réparateur perçu du repos.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR03',
            'dimension' => 'energie-fonctionnement-journee',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous disposé d\'un niveau d\'énergie suffisant pour assurer votre journée habituelle ?',
            'help' => '« Journée habituelle » inclut travail, études, déplacements, tâches domestiques et activités personnelles.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR04',
            'dimension' => 'energie-fonctionnement-journee',
            'text' => 'Au cours des 14 derniers jours, votre énergie est-elle généralement restée suffisamment stable pour aller au bout de vos activités prévues ?',
            'help' => 'Permet d\'identifier une baisse marquée d\'énergie au cours de la journée.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Généralement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Cela dépend fortement des jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR05',
            'dimension' => 'retentissement-fatigue',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence la fatigue vous a-t-elle obligé à réduire, reporter ou abandonner certaines activités habituelles ?',
            'help' => 'Plus la fatigue limite les activités, plus le score est défavorable.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque tous les jours', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR06',
            'dimension' => 'retentissement-fatigue',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence la fatigue a-t-elle diminué votre capacité à rester concentré ou efficace dans vos activités ?',
            'help' => 'Plus l\'impact de la fatigue sur la concentration est fréquent, plus le score est défavorable.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque tous les jours', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR07',
            'dimension' => 'recuperation-apres-effort',
            'text' => 'Après une journée normalement active ou une activité physique habituelle, à quelle fréquence récupérez-vous dans un délai qui vous paraît normal pour vous ?',
            'help' => 'Aucune durée universelle n\'est imposée : la récupération dépend du contexte et de la personne.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR08',
            'dimension' => 'recuperation-apres-effort',
            'text' => 'Après une journée plus exigeante que d\'habitude, à quelle fréquence retrouvez-vous un niveau d\'énergie habituel après une période raisonnable de repos ?',
            'help' => 'Évalue la récupération après une charge temporairement supérieure à l\'habitude.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR09',
            'dimension' => 'efficacite-repos',
            'text' => 'Lorsque vous vous sentez fatigué, une période adaptée de repos ou une pause vous aide-t-elle généralement à retrouver de l\'énergie ?',
            'help' => 'Mesure l\'efficacité perçue du repos.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Généralement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Partiellement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR10',
            'dimension' => 'efficacite-repos',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu besoin de beaucoup plus de repos que d\'habitude pour retrouver votre niveau d\'énergie habituel ?',
            'help' => 'Un besoin fréquent de récupération supplémentaire augmente le score.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque tous les jours', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR11',
            'dimension' => 'stabilite-recuperation-globale',
            'text' => 'Au cours des 14 derniers jours, votre niveau d\'énergie a-t-il été relativement stable d\'un jour à l\'autre ?',
            'help' => 'Des variations normales restent possibles ; la question vise les fluctuations marquées.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très stable', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Généralement stable', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Variable', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent instable', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très instable', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR12',
            'dimension' => 'stabilite-recuperation-globale',
            'text' => 'En considérant globalement les 14 derniers jours, comment évalueriez-vous votre capacité à récupérer entre vos journées et vos activités ?',
            'help' => 'Question intégrative globale du questionnaire.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très bonne', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Bonne', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Moyenne', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Insuffisante', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très insuffisante', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'energie-recuperation-reveil',
            'label' => 'Énergie et récupération au réveil',
            'question_ids' => array('FR01', 'FR02'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'energie-fonctionnement-journee',
            'label' => 'Énergie et fonctionnement dans la journée',
            'question_ids' => array('FR03', 'FR04'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'retentissement-fatigue',
            'label' => 'Retentissement de la fatigue',
            'question_ids' => array('FR05', 'FR06'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'recuperation-apres-effort',
            'label' => 'Récupération après l\'effort',
            'question_ids' => array('FR07', 'FR08'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'efficacite-repos',
            'label' => 'Efficacité du repos',
            'question_ids' => array('FR09', 'FR10'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'stabilite-recuperation-globale',
            'label' => 'Stabilité et récupération globale',
            'question_ids' => array('FR11', 'FR12'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'RECUPERATION_FAVORABLE',
            'rank' => 1,
            'min' => 12,
            'max' => 24,
            'title' => 'Récupération globalement favorable',
            'description' => 'Votre récupération est globalement favorable. D\'après vos réponses, votre niveau de fatigue semble globalement limité et votre capacité de récupération apparaît favorable dans plusieurs dimensions évaluées.',
            'recommendations' => array(
                'Maintenir les habitudes actuelles de récupération',
                'Préserver la régularité du repos',
                'Surveiller les éventuelles baisses d\'énergie',
            ),
        ),
        array(
            'code' => 'RECUPERATION_FRAGILE',
            'rank' => 2,
            'min' => 25,
            'max' => 32,
            'title' => 'Récupération encore fragile',
            'description' => 'Votre récupération reste encore fragile. D\'après vos réponses, vous disposez de certaines capacités de récupération, mais plusieurs dimensions semblent encore fragiles ou irrégulières.',
            'recommendations' => array(
                'Identifier les moments de fatigue les plus marqués',
                'Renforcer les temps de repos et de récupération',
                'Limiter l\'accumulation de surcharge',
            ),
        ),
        array(
            'code' => 'FATIGUE_IMPORTANTE',
            'rank' => 3,
            'min' => 33,
            'max' => 60,
            'title' => 'Fatigue importante / récupération insuffisante',
            'description' => 'Votre fatigue semble actuellement importante et votre récupération insuffisante. D\'après vos réponses, la fatigue semble actuellement avoir un impact important sur plusieurs dimensions de votre quotidien et votre récupération apparaît limitée.',
            'recommendations' => array(
                'Agir en priorité sur les dimensions les plus fragiles',
                'Préserver des périodes régulières de repos',
                'Consulter un professionnel de santé si la fatigue persiste',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'FRSF01',
            'text' => 'Votre fatigue persiste-t-elle depuis plusieurs jours ou semaines malgré un repos suffisant ou des adaptations de vos habitudes ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_SAFETY_MESSAGE')),
            ),
        ),
        array(
            'id' => 'FRSF02',
            'text' => 'Votre fatigue est-elle actuellement si importante qu\'elle vous empêche régulièrement d\'assurer vos activités habituelles ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_SAFETY_MESSAGE')),
            ),
        ),
        array(
            'id' => 'FRSF03',
            'text' => 'Votre fatigue s\'accompagne-t-elle actuellement de signes inhabituels ou d\'une aggravation marquée après des efforts modestes ?',
            'help' => 'Exemples : fièvre, variation de poids involontaire, douleurs inhabituelles, essoufflement marqué, soif inhabituelle, malaise ou récupération anormalement longue après un effort habituellement bien toléré.',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_SAFETY_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'FATIGUE_SAFETY_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Un point mérite votre attention.',
            'text' => 'Une fatigue persistante, très invalidante ou accompagnée de signes inhabituels mérite d’être discutée avec un professionnel de santé.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à décrire la fatigue ressentie, son retentissement au quotidien et la capacité de récupération déclarée.',
        'after' => 'Le Score LifeMetrics - Fatigue & récupération est un outil propriétaire d\'auto-évaluation destiné à fournir un repère informatif sur la fatigue ressentie et la récupération déclarée. Il ne permet pas d\'identifier la cause d\'une fatigue, ne constitue pas un diagnostic médical et ne remplace pas l\'avis d\'un professionnel de santé. Une fatigue persistante, inhabituelle, très invalidante ou associée à d\'autres symptômes mérite un avis médical.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);

