<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'fatigue-recuperation',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Fatigue & récupération',
    'seo_title' => 'Auto-évaluation LifeMetrics - Comment récupérez-vous au quotidien ?',
    'description' => 'Évaluer le profil de fatigue ressentie et la capacité de récupération au quotidien, sans rechercher une cause médicale.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'FR01',
            'dimension' => 'energie-recuperation-reveil',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous réveillé avec suffisamment d\'énergie pour commencer votre journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque tous les jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR02',
            'dimension' => 'energie-recuperation-reveil',
            'text' => 'Après une nuit de sommeil ou une période normale de repos, à quelle fréquence avez-vous eu l\'impression d\'avoir réellement récupéré ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR03',
            'dimension' => 'energie-fonctionnement-journee',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous disposé d\'un niveau d\'énergie suffisant pour assurer votre journée habituelle ?',
            'help' => '« Journée habituelle » inclut travail, études, déplacements, tâches domestiques et activités personnelles.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR04',
            'dimension' => 'energie-fonctionnement-journee',
            'text' => 'Au cours des 14 derniers jours, votre énergie est-elle généralement restée suffisamment stable pour aller au bout de vos activités prévues ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Cela dépend fortement des jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR05',
            'dimension' => 'retentissement-fatigue',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence la fatigue vous a-t-elle obligé à réduire, reporter ou abandonner certaines activités habituelles ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque tous les jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR06',
            'dimension' => 'retentissement-fatigue',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence la fatigue a-t-elle diminué votre capacité à rester concentré ou efficace dans vos activités ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque tous les jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR07',
            'dimension' => 'recuperation-effort',
            'text' => 'Après une journée normalement active ou une activité physique habituelle, à quelle fréquence récupérez-vous dans un délai qui vous paraît normal pour vous ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR08',
            'dimension' => 'recuperation-effort',
            'text' => 'Après une journée plus exigeante que d\'habitude, à quelle fréquence retrouvez-vous un niveau d\'énergie habituel après une période raisonnable de repos ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR09',
            'dimension' => 'efficacite-repos',
            'text' => 'Lorsque vous vous sentez fatigué, une période adaptée de repos ou une pause vous aide-t-elle généralement à retrouver de l\'énergie ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Partiellement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très souvent', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR10',
            'dimension' => 'efficacite-repos',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu besoin de beaucoup plus de repos que d\'habitude pour retrouver votre niveau d\'énergie habituel ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque tous les jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR11',
            'dimension' => 'stabilite-recuperation-globale',
            'text' => 'Au cours des 14 derniers jours, votre niveau d\'énergie a-t-il été relativement stable d\'un jour à l\'autre ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très instable', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent instable', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Variable', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement stable', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très stable', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'FR12',
            'dimension' => 'stabilite-recuperation-globale',
            'text' => 'En considérant globalement les 14 derniers jours, comment évalueriez-vous votre capacité à récupérer entre vos journées et vos activités ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très insuffisante', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Insuffisante', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Moyenne', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Bonne', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très bonne', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'energie-recuperation-reveil',
            'label' => 'Énergie et récupération au réveil',
            'question_ids' => array('FR01', 'FR02'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_ENERGIE_REVEIL',
            ),
        ),
        array(
            'id' => 'energie-fonctionnement-journee',
            'label' => 'Énergie et fonctionnement dans la journée',
            'question_ids' => array('FR03', 'FR04'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_ENERGIE_JOURNEE',
            ),
        ),
        array(
            'id' => 'retentissement-fatigue',
            'label' => 'Retentissement de la fatigue',
            'question_ids' => array('FR05', 'FR06'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_RETENTISSEMENT_FATIGUE',
            ),
        ),
        array(
            'id' => 'recuperation-effort',
            'label' => 'Récupération après l\'effort',
            'question_ids' => array('FR07', 'FR08'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_RECUPERATION_EFFORT',
            ),
        ),
        array(
            'id' => 'efficacite-repos',
            'label' => 'Efficacité du repos',
            'question_ids' => array('FR09', 'FR10'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_EFFICACITE_REPOS',
            ),
        ),
        array(
            'id' => 'stabilite-recuperation-globale',
            'label' => 'Stabilité et récupération globale',
            'question_ids' => array('FR11', 'FR12'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_STABILITE_RECUPERATION',
            ),
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'FATIGUE_IMPORTANTE_RECUPERATION_INSUFFISANTE',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Fatigue importante / récupération insuffisante',
            'description' => 'Vos réponses indiquent que la fatigue semble actuellement avoir un impact important sur plusieurs dimensions de votre quotidien et que votre récupération apparaît limitée.',
            'recommendations' => array(
                'Identifier les dimensions les plus touchées',
                'Préserver suffisamment de temps de repos et de sommeil',
                'Éviter autant que possible l\'accumulation continue de surcharge',
                'Maintenir une activité physique adaptée à vos capacités',
                'Conserver une alimentation et une hydratation régulières',
                'Observer si la situation s\'améliore ou persiste',
            ),
        ),
        array(
            'code' => 'RECUPERATION_A_RENFORCER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Récupération à renforcer',
            'description' => 'Votre profil présente certaines capacités de récupération, mais plusieurs dimensions semblent encore fragiles ou irrégulières.',
            'recommendations' => array(
                'Repérer les deux dimensions les moins bien notées',
                'Conserver les habitudes déjà favorables',
                'Réduire les périodes de surcharge lorsque cela est possible',
                'Observer l\'évolution de l\'énergie et de la récupération dans le temps',
            ),
        ),
        array(
            'code' => 'RECUPERATION_GLOBALEMENT_FAVORABLE',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Récupération globalement favorable',
            'description' => 'Vos réponses décrivent une capacité de récupération globalement favorable. La fatigue semble généralement compatible avec vos activités quotidiennes et le repos permet le plus souvent de retrouver un niveau d\'énergie satisfaisant.',
            'recommendations' => array(
                'Préserver la régularité du sommeil',
                'Maintenir une activité physique adaptée',
                'Conserver des temps de récupération',
                'Surveiller les périodes de surcharge',
                'Identifier les dimensions légèrement inférieures aux autres',
            ),
        ),
        array(
            'code' => 'TRES_BON_PROFIL_RECUPERATION',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Très bon profil de récupération',
            'description' => 'Vos réponses décrivent actuellement un très bon profil de récupération sur les dimensions évaluées.',
            'recommendations' => array(
                'Maintenir cet équilibre dans le temps',
                'Conserver des habitudes favorables de sommeil, d\'activité, d\'alimentation et d\'hydratation',
                'Rester attentif à tout changement inhabituel ou persistant',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(
        'ATTENTION_ENERGIE_REVEIL' => array(
            'title' => 'Point nécessitant une attention particulière : Énergie et récupération au réveil',
            'text' => 'Votre niveau d\'énergie au réveil ou le caractère réparateur de vos nuits est particulièrement faible.',
        ),
        'ATTENTION_ENERGIE_JOURNEE' => array(
            'title' => 'Point nécessitant une attention particulière : Énergie et fonctionnement dans la journée',
            'text' => 'Votre niveau d\'énergie ou sa stabilité au cours de la journée est particulièrement diminué.',
        ),
        'ATTENTION_RETENTISSEMENT_FATIGUE' => array(
            'title' => 'Point nécessitant une attention particulière : Retentissement de la fatigue',
            'text' => 'La fatigue a un impact marqué sur vos activités quotidiennes ou votre concentration.',
        ),
        'ATTENTION_RECUPERATION_EFFORT' => array(
            'title' => 'Point nécessitant une attention particulière : Récupération après l\'effort',
            'text' => 'Votre récupération après une journée active ou un effort physique est anormalement difficile.',
        ),
        'ATTENTION_EFFICACITE_REPOS' => array(
            'title' => 'Point nécessitant une attention particulière : Efficacité du repos',
            'text' => 'Le repos semble peu efficace pour recharger votre énergie ou nécessite des durées anormalement longues.',
        ),
        'ATTENTION_STABILITE_RECUPERATION' => array(
            'title' => 'Point nécessitant une attention particulière : Stabilité et récupération globale',
            'text' => 'Votre récupération globale ou la régularité de votre énergie au fil des jours reste très fragile.',
        ),
    ),
    'safety_questions' => array(
        array(
            'id' => 'FRSF01',
            'text' => 'Votre fatigue persiste-t-elle depuis plusieurs jours ou semaines malgré un repos suffisant ou des adaptations de vos habitudes ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'FRSF02',
            'text' => 'Votre fatigue est-elle actuellement si importante qu\'elle vous empêche régulièrement d\'assurer vos activités habituelles ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'FRSF03',
            'text' => 'Votre fatigue s\'accompagne-t-elle actuellement de signes inhabituels ou d\'une aggravation marquée après des efforts modestes ?',
            'help' => 'Exemples : fièvre, variation de poids involontaire, douleurs inhabituelles, essoufflement marqué, soif inhabituelle, malaise ou récupération anormalement longue après un effort habituellement bien toléré.',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('FATIGUE_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'FATIGUE_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses méritent une attention particulière.',
            'text' => 'Cette auto-évaluation ne permet pas d\'identifier la cause de votre fatigue. Une fatigue persistante malgré le repos, très invalidante ou accompagnée d\'autres symptômes peut nécessiter une évaluation par un professionnel de santé.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir mon bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre votre niveau de fatigue ressenti et votre récupération au quotidien. Elle ne permet pas d\'identifier la cause d\'une fatigue, ne constitue pas un diagnostic médical et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Fatigue & récupération est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories sont conçus à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques. Une fatigue persistante, inhabituelle, très invalidante ou associée à d\'autres symptômes mérite un avis médical.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
