<?php

return array(
    "schema_version" => "2.0.0",
    "id" => "bien-etre",
    "version" => "1.0.0",
    "status" => "review",
    "locale" => "fr-FR",
    "title" => "Score LifeMetrics - Bien-être",
    "seo_title" => "Auto-évaluation LifeMetrics - Bien-être",
    "description" => "Fournir un repère sur le bien-être subjectif récent : satisfaction générale, équilibre émotionnel, engagement, sentiment de maîtrise, sens et connexion sociale.",
    "population" => "Adultes de 18 à 64 ans",
    "recall_period" => "14 derniers jours",
    "estimated_duration" => "2-3 minutes",
    "scoring_direction" => "lower_is_better",
    "score" => array(
        "target_min" => 12,
        "target_max" => 60,
        "normalize_when_unavailable" => false,
        "rounding" => "half_up",
    ),
    "questions" => array(
        array(
            "id" => "BE01",
            "dimension" => "satisfaction-globale-quotidien",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous été satisfait de votre vie quotidienne dans son ensemble ?",
            "help" => "Cette question évalue l'appréciation générale du quotidien, sans chercher à identifier une cause particulière.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très satisfait", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt satisfait", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement satisfait", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Plutôt insatisfait", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très insatisfait", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE02",
            "dimension" => "satisfaction-globale-quotidien",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment que votre quotidien correspondait globalement à ce qui est important pour vous ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Tout à fait", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt oui", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Partiellement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Plutôt non", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE03",
            "dimension" => "equilibre-emotionnel",
            "text" => "Au cours des 14 derniers jours, à quelle fréquence avez-vous ressenti des émotions agréables comme du calme, du plaisir, de la satisfaction ou de la joie ?",
            "help" => "Cette question mesure la présence de ressentis positifs. Elle ne constitue pas un dépistage d'un trouble de l'humeur.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très souvent", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Souvent", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Environ la moitié du temps", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Rarement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque jamais", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE04",
            "dimension" => "equilibre-emotionnel",
            "text" => "Lorsque vous avez vécu un moment difficile au cours des 14 derniers jours, dans quelle mesure avez-vous généralement réussi à retrouver un état émotionnel plus stable ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très facilement", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt facilement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Avec une difficulté modérée", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Difficilement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très difficilement ou presque pas", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE05",
            "dimension" => "engagement-interet-quotidien",
            "text" => "Au cours des 14 derniers jours, à quelle fréquence avez-vous eu suffisamment d'envie ou de motivation pour commencer les activités prévues dans votre journée ?",
            "help" => "Cette question évalue l'engagement subjectif dans le quotidien et non directement la fatigue physique.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Presque toujours", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Souvent", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Environ la moitié du temps", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Rarement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque jamais", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE06",
            "dimension" => "engagement-interet-quotidien",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure vos activités habituelles vous ont-elles semblé intéressantes ou engageantes ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très souvent intéressantes ou engageantes", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Souvent", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Rarement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Presque jamais", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE07",
            "dimension" => "maitrise-capacite-faire-face",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment de pouvoir gérer les exigences ordinaires de votre quotidien ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très bien", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt bien", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Difficilement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très difficilement", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE08",
            "dimension" => "maitrise-capacite-faire-face",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment de garder une certaine maîtrise sur l'organisation de votre vie quotidienne ?",
            "help" => "BE07 porte sur la capacité perçue à gérer le quotidien ; BE08 porte davantage sur le sentiment de contrôle et d'organisation.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très fortement", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt fortement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Faiblement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très faiblement ou pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE09",
            "dimension" => "sens-accomplissement-personnel",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment que ce que vous faisiez au quotidien avait du sens pour vous ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très fortement", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt fortement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Faiblement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE10",
            "dimension" => "sens-accomplissement-personnel",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment d'avancer vers des objectifs ou des choses importantes pour vous ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très nettement", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt nettement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Modérément", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Peu", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE11",
            "dimension" => "connexion-sociale-ressentie",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure vous êtes-vous senti suffisamment connecté aux personnes qui comptent pour vous ?",
            "help" => "La question porte sur le ressenti de connexion sociale et non sur le nombre objectif de relations.",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Très fortement", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt fortement", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Moyennement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Faiblement", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Très faiblement ou pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
        array(
            "id" => "BE12",
            "dimension" => "connexion-sociale-ressentie",
            "text" => "Au cours des 14 derniers jours, dans quelle mesure avez-vous eu le sentiment de pouvoir compter sur quelqu'un si vous aviez besoin de soutien ?",
            "required" => true,
            "answers" => array(
                array("value" => "1", "label" => "Tout à fait", "points" => 1, "applicable" => true),
                array("value" => "2", "label" => "Plutôt oui", "points" => 2, "applicable" => true),
                array("value" => "3", "label" => "Partiellement", "points" => 3, "applicable" => true),
                array("value" => "4", "label" => "Plutôt non", "points" => 4, "applicable" => true),
                array("value" => "5", "label" => "Pas du tout", "points" => 5, "applicable" => true),
            ),
        ),
    ),
    "dimensions" => array(
        array(
            "id" => "satisfaction-globale-quotidien",
            "label" => "Satisfaction globale du quotidien",
            "question_ids" => array("BE01", "BE02"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "equilibre-emotionnel",
            "label" => "Équilibre émotionnel",
            "question_ids" => array("BE03", "BE04"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "engagement-interet-quotidien",
            "label" => "Engagement et intérêt dans le quotidien",
            "question_ids" => array("BE05", "BE06"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "maitrise-capacite-faire-face",
            "label" => "Maîtrise et capacité à faire face",
            "question_ids" => array("BE07", "BE08"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "sens-accomplissement-personnel",
            "label" => "Sens et accomplissement personnel",
            "question_ids" => array("BE09", "BE10"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
        array(
            "id" => "connexion-sociale-ressentie",
            "label" => "Connexion sociale ressentie",
            "question_ids" => array("BE11", "BE12"),
            "calculation_mode" => "average",
            "weakest_eligible" => true,
        ),
    ),
    "weakest_dimensions" => array(
        "count" => 2,
        "tie_break" => "configuration_order",
    ),
    "result_levels" => array(
        array(
            "code" => "BIEN_ETRE_FAVORABLE",
            "rank" => 1,
            "min" => 12,
            "max" => 24,
            "title" => "Bien-être globalement favorable",
            "description" => "Votre bien-être est globalement favorable. D'après vos réponses, votre perception récente du quotidien est globalement positive. Vous semblez conserver des ressources satisfaisantes dans plusieurs dimensions importantes : satisfaction générale, équilibre émotionnel, engagement, capacité à gérer le quotidien, sentiment de sens et connexion avec les autres. Certaines dimensions peuvent rester ponctuellement moins favorables, mais elles ne semblent pas actuellement fragiliser fortement votre bien-être global.",
            "recommendations" => array(
                "Maintenir les éléments actuellement favorables",
                "Suivre dans le temps les éventuelles dimensions qui évoluent moins bien",
            ),
        ),
        array(
            "code" => "BIEN_ETRE_A_RENFORCER",
            "rank" => 2,
            "min" => 25,
            "max" => 32,
            "title" => "Bien-être à renforcer",
            "description" => "Votre bien-être présente plusieurs dimensions à renforcer. Vos réponses montrent que vous conservez certaines ressources positives, mais que plusieurs aspects de votre quotidien sont actuellement moins favorables. Cela peut concerner votre satisfaction générale, votre équilibre émotionnel, votre engagement, votre sentiment de maîtrise, le sens que vous trouvez dans vos activités ou votre connexion aux autres. Votre résultat correspond donc à une situation intermédiaire : votre bien-être n'est pas uniformément défavorable, mais certaines fragilités sont suffisamment présentes pour mériter une attention particulière.",
            "recommendations" => array(
                "Identifier les dimensions les moins favorables",
                "Concentrer en priorité votre attention sur celles qui ont le plus d'impact sur votre quotidien",
            ),
        ),
        array(
            "code" => "BIEN_ETRE_FRAGILISE",
            "rank" => 3,
            "min" => 33,
            "max" => 60,
            "title" => "Bien-être global fragilisé",
            "description" => "Votre bien-être global est actuellement fragilisé. Vos réponses indiquent que plusieurs dimensions importantes de votre bien-être sont actuellement défavorables. Vous pouvez notamment ressentir une satisfaction réduite dans votre quotidien, moins d'émotions positives, une diminution de l'engagement, un sentiment de moindre maîtrise, moins de sens ou d'accomplissement, ou une connexion sociale insuffisante. Le résultat ne permet pas d'en déterminer la cause, mais il montre que ces difficultés ne sont pas limitées à un seul aspect isolé de votre quotidien.",
            "recommendations" => array(
                "Identifier les dimensions les plus faibles et suivre leur évolution",
                "Envisager un échange avec un professionnel de santé si votre mal-être est important, persistant ou affecte fortement votre fonctionnement quotidien",
            ),
        ),
    ),
    "classification_rules" => array(
        array(
            "id" => "BE_GUARDRAIL_SATISFACTION",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "satisfaction-globale-quotidien",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_SATISFACTION_MSG",
        ),
        array(
            "id" => "BE_GUARDRAIL_EMOTIONNEL",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "equilibre-emotionnel",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_EMOTIONNEL_MSG",
        ),
        array(
            "id" => "BE_GUARDRAIL_ENGAGEMENT",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "engagement-interet-quotidien",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_ENGAGEMENT_MSG",
        ),
        array(
            "id" => "BE_GUARDRAIL_MAITRISE",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "maitrise-capacite-faire-face",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_MAITRISE_MSG",
        ),
        array(
            "id" => "BE_GUARDRAIL_SENS",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "sens-accomplissement-personnel",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_SENS_MSG",
        ),
        array(
            "id" => "BE_GUARDRAIL_CONNEXION",
            "type" => "category_cap",
            "metric" => "dimension_score",
            "dimension" => "connexion-sociale-ressentie",
            "operator" => ">=",
            "value" => 8,
            "max_category" => "BIEN_ETRE_A_RENFORCER",
            "message_code" => "BE_GUARDRAIL_CONNEXION_MSG",
        ),
    ),
    "classification_messages" => array(
        "BE_GUARDRAIL_SATISFACTION_MSG" => array(
            "title" => "Point d'attention : Satisfaction globale du quotidien",
            "text" => "Une fragilité marquée dans la satisfaction globale du quotidien a été constatée.",
        ),
        "BE_GUARDRAIL_EMOTIONNEL_MSG" => array(
            "title" => "Point d'attention : Équilibre émotionnel",
            "text" => "Une fragilité marquée dans l'équilibre émotionnel a été constatée.",
        ),
        "BE_GUARDRAIL_ENGAGEMENT_MSG" => array(
            "title" => "Point d'attention : Engagement et intérêt dans le quotidien",
            "text" => "Une fragilité marquée dans l'engagement et l'intérêt du quotidien a été constatée.",
        ),
        "BE_GUARDRAIL_MAITRISE_MSG" => array(
            "title" => "Point d'attention : Maîtrise et capacité à faire face",
            "text" => "Une fragilité marquée dans le sentiment de maîtrise et la gestion du quotidien a été constatée.",
        ),
        "BE_GUARDRAIL_SENS_MSG" => array(
            "title" => "Point d'attention : Sens et accomplissement personnel",
            "text" => "Une fragilité marquée dans le sentiment de sens ou d'accomplissement a été constatée.",
        ),
        "BE_GUARDRAIL_CONNEXION_MSG" => array(
            "title" => "Point d'attention : Connexion sociale ressentie",
            "text" => "Une fragilité marquée dans le sentiment de connexion sociale a été constatée.",
        ),
    ),
    "improvement_messages" => array(
        "satisfaction-globale-quotidien" => array(
            "title" => "Satisfaction globale du quotidien",
            "text" => "Identifier les éléments du quotidien qui génèrent le plus d'insatisfaction et réfléchir à des ajustements progressifs.",
        ),
        "equilibre-emotionnel" => array(
            "title" => "Équilibre émotionnel",
            "text" => "Prendre du temps pour des activités ressources et pratiquer des techniques de régulation émotionnelle.",
        ),
        "engagement-interet-quotidien" => array(
            "title" => "Engagement et intérêt dans le quotidien",
            "text" => "Réintroduire progressivement des projets, centres d'intérêt ou activités motivantes dans vos journées.",
        ),
        "maitrise-capacite-faire-face" => array(
            "title" => "Maîtrise et capacité à faire face",
            "text" => "Clarifier les priorités quotidiennes, simplifier l'organisation et ne pas hésiter à déléguer.",
        ),
        "sens-accomplissement-personnel" => array(
            "title" => "Sens et accomplissement personnel",
            "text" => "Se reconnecter à ce qui a une valeur personnelle importante et définir de petits objectifs gratifiants.",
        ),
        "connexion-sociale-ressentie" => array(
            "title" => "Connexion sociale ressentie",
            "text" => "Entretenir les liens avec les proches et rechercher des occasions d'échange et de soutien mutuel.",
        ),
    ),
    "safety_questions" => array(),
    "safety_messages" => array(),
    "result_ctas" => array(
        array(
            "label" => "Je veux faire un bilan",
            "url" => "https://lifemetrics.fr/formulaire-bilan/",
            "variant" => "primary",
            "enabled" => true,
        ),
        array(
            "label" => "Découvrir les autres questionnaires",
            "url" => "/tests-sante/",
            "variant" => "secondary",
            "enabled" => true,
        ),
    ),
    "funnel" => array(
        "title" => "Suivre l'évolution de votre bien-être",
        "text" => "Ce questionnaire fournit une photographie de votre bien-être subjectif au cours des 14 derniers jours. L'intérêt principal est de pouvoir suivre son évolution dans le temps et d'identifier les dimensions qui progressent, restent stables ou se fragilisent. Les dimensions moins favorables peuvent également orienter vers d'autres questionnaires LifeMetrics plus spécifiques lorsque cela est pertinent. Parcours : Évaluer mon bien-être → comprendre mes dimensions → approfondir si nécessaire → refaire le questionnaire → suivre l'évolution.",
        "partner_cta_label" => "Suivre l'évolution de mon bien-être",
    ),
    "disclaimer" => array(
        "before" => "Cette auto-évaluation LifeMetrics est destinée à fournir un repère sur le bien-être subjectif récent.",
        "after" => "Le Score LifeMetrics - Bien-être est un outil propriétaire d'auto-évaluation destiné à fournir un repère sur le bien-être subjectif récent. Il ne constitue pas un diagnostic médical ou psychologique et ne remplace pas l'évaluation d'un professionnel de santé. Le score et les catégories sont des niveaux d'interprétation LifeMetrics et ne constituent pas des seuils diagnostiques ou cliniques. Le questionnaire ne permet pas de diagnostiquer une dépression, un trouble anxieux, un burn-out ou une autre pathologie.",
    ),
    "disclaimers" => array(
        "general" => "Le Score LifeMetrics - Bien-être est un outil propriétaire d'auto-évaluation destiné à fournir un repère sur le bien-être subjectif récent. Il ne constitue pas un diagnostic médical ou psychologique et ne remplace pas l'évaluation d'un professionnel de santé. Le score et les catégories sont des niveaux d'interprétation LifeMetrics et ne constituent pas des seuils diagnostiques ou cliniques.",
        "scientific" => "Le questionnaire repose sur la perception et les réponses déclarées par l'utilisateur au cours des 14 derniers jours. Le résultat peut être influencé par des événements récents ainsi que par le contexte personnel, professionnel ou social. Il ne permet pas de diagnostiquer une dépression, un trouble anxieux, un burn-out ou une autre pathologie. Il ne permet pas non plus d'identifier automatiquement la cause d'un niveau de bien-être faible. Le questionnaire ne mesure pas directement le sommeil, l'activité physique, la nutrition, la condition physique ou la composition corporelle. Un résultat favorable ne garantit pas l'absence d'un problème de santé, et un résultat défavorable ne signifie pas automatiquement qu'une pathologie est présente.",
    ),
    "approvals" => array(
        "content_scoring" => true,
        "legal_licensing" => false,
        "technical_runtime" => true,
        "publication" => false,
    ),
);
