<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'sedentarite',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Sédentarité',
    'description' => 'Évaluez le volume, la continuité et l\'interruption de votre sédentarité quotidienne, indépendamment de votre niveau sportif.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => true,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'SD01',
            'dimension' => 'temps-sedentaire-quotidien',
            'text' => 'Au cours des 14 derniers jours, combien de temps avez-vous passé en moyenne assis ou allongé pendant vos heures d\'éveil ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 9 heures par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Entre 7 et 9 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Entre 5 et moins de 7 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Entre 3 et moins de 5 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Moins de 3 heures', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD02',
            'dimension' => 'temps-sedentaire-quotidien',
            'text' => 'Au cours des 14 derniers jours, combien de jours par semaine avez-vous passé une très grande partie de votre journée éveillée en position assise ou allongée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => '6-7 jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '4-5 jours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '3 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-2 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement ou jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD03',
            'dimension' => 'continuite-periodes-assises',
            'text' => 'Lorsque vous travaillez, étudiez ou vous détendez, combien de temps restez-vous généralement assis sans vous lever ni marcher quelques minutes ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 2 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Entre 90 et 120 minutes', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Entre 60 et 89 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Entre 30 et 59 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Généralement moins de 30 minutes', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD04',
            'dimension' => 'continuite-periodes-assises',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous passé au moins deux heures presque entièrement assis sans véritable interruption de mouvement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plusieurs fois par jour', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Environ une fois par jour', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Plusieurs fois par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD05',
            'dimension' => 'ruptures-sedentarite',
            'text' => 'Lorsque vous restez assis pendant une période prolongée, à quelle fréquence vous levez-vous pour marcher ou bouger quelques minutes ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Généralement après plus de 2 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ toutes les 1 à 2 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ toutes les 30 à 60 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Environ toutes les 30 minutes ou plus souvent', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD06',
            'dimension' => 'ruptures-sedentarite',
            'text' => 'Lorsque vous interrompez une période assise, que faites-vous généralement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Je reste assis ou change seulement de position', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Je me lève brièvement sans réellement bouger', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Je reste debout ou bouge moins d\'une minute', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Je marche ou bouge quelques minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Je marche ou bouge généralement environ 3 à 5 minutes ou davantage', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD07',
            'dimension' => 'travail-etudes-deplacements',
            'text' => 'Pendant vos périodes de travail ou d\'études, à quelle fréquence alternez-vous volontairement les périodes assises avec des moments debout ou en mouvement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulièrement', 'points' => 4, 'applicable' => true),
                array('value' => 'na', 'label' => 'Non concerné actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'SD08',
            'dimension' => 'travail-etudes-deplacements',
            'text' => 'Pour vos déplacements habituels, quelle part du trajet est généralement passée assis dans une voiture, les transports ou un autre véhicule ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque tous mes déplacements sont entièrement assis', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Une très grande majorité', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Une minorité seulement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très peu / je me déplace principalement à pied ou autrement en mouvement', 'points' => 4, 'applicable' => true),
                array('value' => 'na', 'label' => 'Très peu de déplacements actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'SD09',
            'dimension' => 'loisirs-sedentaires',
            'text' => 'En dehors du travail ou des études, combien de temps passez-vous généralement assis devant un écran au cours d\'une journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 5 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '4-5 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2-4 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '1-2 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Moins d\'une heure', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD10',
            'dimension' => 'loisirs-sedentaires',
            'text' => 'Lorsque vous regardez un écran ou réalisez une activité de loisir assise pendant longtemps, à quelle fréquence profitez-vous d\'une occasion pour vous lever ou bouger ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulièrement', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD11',
            'dimension' => 'mouvement-quotidien-regularite',
            'text' => 'En dehors de vos séances de sport éventuelles, à quelle fréquence intégrez-vous de petits moments de mouvement dans votre journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Quelques fois dans la journée', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Régulièrement dans la journée', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulièrement tout au long de la journée', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD12',
            'dimension' => 'mouvement-quotidien-regularite',
            'text' => 'Au cours des 14 derniers jours, avez-vous réussi à limiter et interrompre régulièrement les longues périodes assises, y compris les jours de travail, d\'études et les week-ends ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Cela dépend fortement des jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'temps-sedentaire-quotidien',
            'label' => 'Temps sédentaire quotidien',
            'question_ids' => array('SD01', 'SD02'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_TEMPS_SEDENTAIRE',
            ),
        ),
        array(
            'id' => 'continuite-periodes-assises',
            'label' => 'Continuité des périodes assises',
            'question_ids' => array('SD03', 'SD04'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_CONTINUITE_ASSISES',
            ),
        ),
        array(
            'id' => 'ruptures-sedentarite',
            'label' => 'Ruptures de sédentarité',
            'question_ids' => array('SD05', 'SD06'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_RUPTURES_SEDENTARITE',
            ),
        ),
        array(
            'id' => 'travail-etudes-deplacements',
            'label' => 'Travail / études et déplacements',
            'question_ids' => array('SD07', 'SD08'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'percentage',
                'operator' => '<=',
                'value' => 25,
                'message_code' => 'ATTENTION_TRAVAIL_DEPLACEMENTS',
            ),
        ),
        array(
            'id' => 'loisirs-sedentaires',
            'label' => 'Loisirs sédentaires',
            'question_ids' => array('SD09', 'SD10'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_LOISIRS_SEDENTAIRES',
            ),
        ),
        array(
            'id' => 'mouvement-quotidien-regularite',
            'label' => 'Mouvement quotidien et régularité',
            'question_ids' => array('SD11', 'SD12'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_MOUVEMENT_REGULARITE',
            ),
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'SEDENTARITE_ELEVEE',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Sédentarité élevée',
            'description' => 'Vos réponses décrivent un quotidien actuellement marqué par un temps sédentaire important et/ou par de longues périodes passées assis sans interruption.',
            'recommendations' => array(
                'Vous lever plus souvent',
                'Marcher quelques minutes pendant les longues périodes assises',
                'Utiliser les appels, pauses ou changements de tâche comme déclencheurs de mouvement',
                'Réduire progressivement certaines longues périodes assises',
                'Intégrer davantage de mouvement léger dans la journée',
            ),
        ),
        array(
            'code' => 'SEDENTARITE_A_REDUIRE',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Sédentarité à réduire',
            'description' => 'Vous avez déjà certaines habitudes favorables, mais votre journée contient encore plusieurs périodes de sédentarité qui peuvent être réduites ou interrompues plus régulièrement.',
            'recommendations' => array(
                'Temps total assis',
                'Continuité des périodes assises',
                'Pauses régulières',
                'Organisation du travail / études',
                'Gestion des déplacements',
                'Loisirs actifs',
                'Mouvement quotidien',
            ),
        ),
        array(
            'code' => 'HABITUDES_SEDENTARITE_GLOBALEMENT_FAVORABLES',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Habitudes globalement favorables',
            'description' => 'Vos réponses décrivent des habitudes globalement favorables concernant la réduction et l\'interruption de la sédentarité.',
            'recommendations' => array(
                'Conserver des ruptures régulières',
                'Éviter les séquences assises très longues',
                'Maintenir du mouvement léger au fil de la journée',
                'Surveiller les dimensions encore plus faibles, notamment loisirs ou déplacements',
            ),
        ),
        array(
            'code' => 'TRES_BONNES_HABITUDES_ANTI_SEDENTARITE',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Très bonnes habitudes anti-sédentarité',
            'description' => 'Votre profil indique des habitudes particulièrement favorables sur les dimensions évaluées.',
            'recommendations' => array(
                'Limiter votre temps assis',
                'Éviter de longues séquences ininterrompues',
                'Vous lever régulièrement',
                'Intégrer naturellement du mouvement dans votre journée',
            ),
        ),
    ),
    'classification_rules' => array(
        array(
            'id' => 'CAP_HIGH_SEDENTARY_TIME',
            'type' => 'category_cap',
            'metric' => 'dimension_score',
            'dimension' => 'temps-sedentaire-quotidien',
            'operator' => '<=',
            'value' => 2,
            'max_category' => 'SEDENTARITE_A_REDUIRE',
            'message_code' => 'SEDENTARITE_VOLUME_CAP',
        ),
    ),
    'classification_messages' => array(
        'SEDENTARITE_VOLUME_CAP' => array(
            'title' => 'Temps assis quotidien élevé',
            'text' => 'Votre score global reflète de bonnes habitudes d\'interruption de la position assise. Cependant, le temps total passé assis reste élevé. Des pauses fréquentes sont favorables, mais elles ne compensent pas entièrement un volume quotidien important de sédentarité.',
        ),
        'ATTENTION_TEMPS_SEDENTAIRE' => array(
            'title' => 'Point nécessitant une attention particulière : Temps sédentaire quotidien',
            'text' => 'Votre temps assis ou allongé quotidien cumulé est particulièrement élevé.',
        ),
        'ATTENTION_CONTINUITE_ASSISES' => array(
            'title' => 'Point nécessitant une attention particulière : Continuité des périodes assises',
            'text' => 'Vos périodes assises ininterrompues sont souvent trop longues.',
        ),
        'ATTENTION_RUPTURES_SEDENTARITE' => array(
            'title' => 'Point nécessitant une attention particulière : Ruptures de sédentarité',
            'text' => 'Vos interruptions de position assise sont trop rares ou trop brèves.',
        ),
        'ATTENTION_TRAVAIL_DEPLACEMENTS' => array(
            'title' => 'Point nécessitant une attention particulière : Travail, études et déplacements',
            'text' => 'Vos contextes de travail, d\'études ou de transport contribuent fortement à votre sédentarité.',
        ),
        'ATTENTION_LOISIRS_SEDENTAIRES' => array(
            'title' => 'Point nécessitant une attention particulière : Loisirs sédentaires',
            'text' => 'Votre temps d\'écran ou de loisir assis est particulièrement important.',
        ),
        'ATTENTION_MOUVEMENT_REGULARITE' => array(
            'title' => 'Point nécessitant une attention particulière : Mouvement quotidien et régularité',
            'text' => 'Le mouvement léger et la régularité des habitudes méritent d\'être renforcés.',
        ),
    ),
    'safety_questions' => array(),
    'safety_messages' => array(),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir mon bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre vos habitudes de sédentarité. Elle ne constitue pas un diagnostic médical et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Sédentarité est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories sont conçus à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques. Cas particuliers : si votre mobilité est limitée par votre état de santé, un handicap, une douleur, une grossesse ou une recommandation médicale particulière, adaptez les conseils de mouvement à votre situation et demandez conseil à un professionnel de santé si nécessaire.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
