<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'sedentarite',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Sédentarité',
    'seo_title' => 'Auto-évaluation LifeMetrics - Sédentarité',
    'description' => 'Évaluez le volume, la continuité et l\'interruption de votre sédentarité quotidienne, indépendamment de votre niveau sportif.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => true,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'SD01',
            'dimension' => 'temps-sedentaire-quotidien',
            'text' => 'Au cours des 14 derniers jours, combien de temps avez-vous passé en moyenne assis ou allongé pendant vos heures d\'éveil ?',
            'help' => 'Inclure travail/études, repas, déplacements, télévision, ordinateur, jeux vidéo, téléphone et autres loisirs assis. Ne pas compter le sommeil. Les seuils constituent une gradation LifeMetrics.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Moins de 3 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Entre 3 et moins de 5 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Entre 5 et moins de 7 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Entre 7 et 9 heures', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Plus de 9 heures par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD02',
            'dimension' => 'temps-sedentaire-quotidien',
            'text' => 'Au cours des 14 derniers jours, combien de jours par semaine avez-vous passé une très grande partie de votre journée éveillée en position assise ou allongée ?',
            'help' => 'Complète SD01 en mesurant la fréquence des journées particulièrement sédentaires.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Rarement ou jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1-2 jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '3 jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '4-5 jours', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => '6-7 jours', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD03',
            'dimension' => 'continuite-periodes-assises',
            'text' => 'Lorsque vous travaillez, étudiez ou vous détendez, combien de temps restez-vous généralement assis sans vous lever ni marcher quelques minutes ?',
            'help' => 'Gradation LifeMetrics informée par les recommandations récentes sur les ruptures fréquentes de sédentarité.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Généralement moins de 30 minutes', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Entre 30 et 59 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Entre 60 et 89 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Entre 90 et 120 minutes', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Plus de 2 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD04',
            'dimension' => 'continuite-periodes-assises',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous passé au moins deux heures presque entièrement assis sans véritable interruption de mouvement ?',
            'help' => 'Plus les longues séquences assises sont fréquentes, plus le score est défavorable.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Plusieurs fois par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Environ une fois par jour', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Plusieurs fois par jour', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD05',
            'dimension' => 'ruptures-sedentarite',
            'text' => 'Lorsque vous restez assis pendant une période prolongée, à quelle fréquence vous levez-vous pour marcher ou bouger quelques minutes ?',
            'help' => 'Les données Anses soutiennent des ruptures régulières, avec un bénéfice particulièrement favorable autour de 30 minutes.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Environ toutes les 30 minutes ou plus souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ toutes les 30 à 60 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ toutes les 1 à 2 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Généralement après plus de 2 heures', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD06',
            'dimension' => 'ruptures-sedentarite',
            'text' => 'Lorsque vous interrompez une période assise, que faites-vous généralement ?',
            'help' => 'Le but n’est pas de transformer chaque pause en séance de sport : quelques minutes de mouvement léger constituent déjà une rupture utile.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Je marche ou bouge généralement environ 3 à 5 minutes ou davantage', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Je marche ou bouge quelques minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Je reste debout ou bouge moins d’une minute', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Je me lève brièvement sans réellement bouger', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Je reste assis ou change seulement de position', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD07',
            'dimension' => 'travail-etudes-deplacements',
            'text' => 'Pendant vos périodes de travail ou d\'études, à quelle fréquence alternez-vous volontairement les périodes assises avec des moments debout ou en mouvement ?',
            'help' => '« Non concerné actuellement » reste hors score.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très régulièrement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
                array('value' => 'na', 'label' => 'Non concerné actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'SD08',
            'dimension' => 'travail-etudes-deplacements',
            'text' => 'Pour vos déplacements habituels, quelle part du trajet est généralement passée assis dans une voiture, les transports ou un autre véhicule ?',
            'help' => 'Cette question mesure la contribution des déplacements au temps sédentaire, pas la performance sportive. « Très peu de déplacements actuellement » reste hors score.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très peu / je me déplace principalement à pied ou autrement en mouvement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Une minorité seulement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Une très grande majorité', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque tous mes déplacements sont entièrement assis', 'points' => 5, 'applicable' => true),
                array('value' => 'na', 'label' => 'Très peu de déplacements actuellement', 'points' => null, 'applicable' => false),
            ),
        ),
        array(
            'id' => 'SD09',
            'dimension' => 'loisirs-sedentaires',
            'text' => 'En dehors du travail ou des études, combien de temps passez-vous généralement assis devant un écran au cours d\'une journée ?',
            'help' => 'Gradation comportementale LifeMetrics ; il ne s’agit pas d’un seuil médical universel de screen time.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Moins d’une heure', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '1-2 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '2-4 heures', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '4-5 heures', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Plus de 5 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD10',
            'dimension' => 'loisirs-sedentaires',
            'text' => 'Lorsque vous regardez un écran ou réalisez une activité de loisir assise pendant longtemps, à quelle fréquence profitez-vous d\'une occasion pour vous lever ou bouger ?',
            'help' => 'Exemples : entre deux épisodes, pendant une pause, entre deux parties ou pendant un appel.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très régulièrement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD11',
            'dimension' => 'mouvement-quotidien-regularite',
            'text' => 'En dehors de vos séances de sport éventuelles, à quelle fréquence intégrez-vous de petits moments de mouvement dans votre journée ?',
            'help' => 'Exemples : marcher quelques minutes, escaliers, tâche domestique, appel debout, petits déplacements.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très régulièrement tout au long de la journée', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Régulièrement dans la journée', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Quelques fois dans la journée', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SD12',
            'dimension' => 'mouvement-quotidien-regularite',
            'text' => 'Au cours des 14 derniers jours, avez-vous réussi à limiter et interrompre régulièrement les longues périodes assises, y compris les jours de travail, d\'études et les week-ends ?',
            'help' => 'Question intégrative LifeMetrics sur la stabilité des habitudes.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Généralement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Cela dépend fortement des jours', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'temps-sedentaire-quotidien',
            'label' => 'Temps sédentaire quotidien',
            'question_ids' => array('SD01', 'SD02'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'continuite-periodes-assises',
            'label' => 'Continuité des périodes assises',
            'question_ids' => array('SD03', 'SD04'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'ruptures-sedentarite',
            'label' => 'Ruptures de sédentarité',
            'question_ids' => array('SD05', 'SD06'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'travail-etudes-deplacements',
            'label' => 'Travail / études et déplacements',
            'question_ids' => array('SD07', 'SD08'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'loisirs-sedentaires',
            'label' => 'Loisirs sédentaires',
            'question_ids' => array('SD09', 'SD10'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'mouvement-quotidien-regularite',
            'label' => 'Mouvement quotidien et régularité',
            'question_ids' => array('SD11', 'SD12'),
            'calculation_mode' => 'average',
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'HABITUDES_FAVORABLES',
            'rank' => 1,
            'min' => 12,
            'max' => 24,
            'title' => 'Habitudes de sédentarité globalement favorables',
            'description' => 'Vos habitudes vis-à-vis de la sédentarité sont globalement favorables. D’après vos réponses, votre quotidien présente globalement des habitudes favorables concernant le temps passé assis et l’interruption des périodes sédentaires.',
            'recommendations' => array(
                'Conserver des ruptures régulières',
                'Éviter les séquences assises très longues',
                'Maintenir du mouvement léger au fil de la journée',
            ),
        ),
        array(
            'code' => 'SEDENTARITE_A_REDUIRE',
            'rank' => 2,
            'min' => 25,
            'max' => 32,
            'title' => 'Sédentarité à réduire',
            'description' => 'Votre sédentarité reste à réduire. D’après vos réponses, vous avez déjà certaines habitudes favorables, mais votre quotidien comporte encore plusieurs périodes de sédentarité qui pourraient être réduites ou interrompues plus régulièrement.',
            'recommendations' => array(
                'Réduire les plus longues périodes assises',
                'Multiplier les courtes interruptions actives',
                'Augmenter le mouvement léger dans la journée',
            ),
        ),
        array(
            'code' => 'SEDENTARITE_ELEVEE',
            'rank' => 3,
            'min' => 33,
            'max' => 60,
            'title' => 'Sédentarité élevée',
            'description' => 'Votre niveau de sédentarité est actuellement élevé. D’après vos réponses, votre quotidien est actuellement marqué par un temps sédentaire important et/ou par des périodes prolongées passées assis avec trop peu d’interruptions.',
            'recommendations' => array(
                'Interrompre plus souvent la position assise',
                'Réduire progressivement le temps assis total',
                'Intégrer davantage de mouvement léger chaque jour',
            ),
        ),
    ),
    'classification_rules' => array(
        array(
            'id' => 'GUARDRAIL_TEMPS_SEDENTAIRE_D1',
            'type' => 'category_cap',
            'metric' => 'dimension_score',
            'dimension' => 'temps-sedentaire-quotidien',
            'operator' => '>=',
            'value' => 8,
            'max_category' => 'SEDENTARITE_A_REDUIRE',
            'message_code' => 'SEDENTARITE_VOLUME_CAP',
        ),
    ),
    'classification_messages' => array(
        'SEDENTARITE_VOLUME_CAP' => array(
            'title' => 'Temps quotidien assis important',
            'text' => 'Votre score global reflète plusieurs habitudes favorables concernant l’interruption de la position assise. Cependant, votre temps total passé assis reste élevé. Des pauses régulières sont bénéfiques, mais elles ne compensent pas entièrement un volume quotidien important de sédentarité.',
        ),
    ),
    'safety_questions' => array(),
    'safety_messages' => array(),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre le volume, la continuité et l’interruption de votre sédentarité quotidienne.',
        'after' => 'Le Score LifeMetrics - Sédentarité est un outil propriétaire d’auto-évaluation destiné à fournir un repère informatif sur les habitudes de sédentarité. Il ne constitue pas un diagnostic médical et ne remplace pas l’avis d’un professionnel de santé. Si votre mobilité est limitée par votre état de santé, un handicap, une douleur, une grossesse ou une recommandation médicale particulière, les conseils de mouvement doivent être adaptés à votre situation.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);

