<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'sommeil',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Sommeil',
    'seo_title' => 'Auto-évaluation LifeMetrics - Sommeil',
    'description' => 'Le Score LifeMetrics - Sommeil est une auto-évaluation destinée à aider une personne à mieux comprendre la qualité globale de son sommeil et son retentissement dans la vie quotidienne.',
    'population' => 'Adultes',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'SL01',
            'dimension' => 'duree-suffisance-sommeil',
            'text' => 'Au cours des 14 derniers jours, combien de temps avez-vous dormi en moyenne par nuit ?',
            'help' => 'Il s\'agit du temps réellement dormi estimé et non de l\'ensemble du temps passé au lit.',
            'required' => true,
            'answers' => array(
                array('value' => '7_to_9h', 'label' => '7 h à 9 h', 'points' => 1, 'applicable' => true),
                array('value' => 'more_9h', 'label' => 'Plus de 9 h', 'points' => 2, 'applicable' => true),
                array('value' => '6_to_7h', 'label' => '6 h à moins de 7 h', 'points' => 3, 'applicable' => true),
                array('value' => '5_to_6h', 'label' => '5 h à moins de 6 h', 'points' => 4, 'applicable' => true),
                array('value' => 'less_5h', 'label' => 'Moins de 5 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL02',
            'dimension' => 'duree-suffisance-sommeil',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu l\'impression d\'avoir dormi suffisamment longtemps pour vos besoins ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL03',
            'dimension' => 'endormissement-continuite',
            'text' => 'Au cours des 14 derniers jours, combien de temps vous fallait-il généralement pour vous endormir après avoir décidé de dormir ?',
            'required' => true,
            'answers' => array(
                array('value' => '15_min_or_less', 'label' => '15 minutes ou moins', 'points' => 1, 'applicable' => true),
                array('value' => '16_to_30_min', 'label' => '16 à 30 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '31_to_45_min', 'label' => '31 à 45 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '46_to_60_min', 'label' => '46 à 60 minutes', 'points' => 4, 'applicable' => true),
                array('value' => 'more_60_min', 'label' => 'Plus de 60 minutes', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL04',
            'dimension' => 'endormissement-continuite',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre sommeil a-t-il été interrompu par des réveils qui vous ont réellement gêné ?',
            'required' => true,
            'answers' => array(
                array('value' => 'rarely_never', 'label' => 'Rarement ou jamais', 'points' => 1, 'applicable' => true),
                array('value' => '1_night_week', 'label' => 'Environ 1 nuit par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '2_3_nights_week', 'label' => '2-3 nuits par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4_5_nights_week', 'label' => '4-5 nuits par semaine', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_every_night', 'label' => 'Presque chaque nuit', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL05',
            'dimension' => 'endormissement-continuite',
            'text' => 'Lorsque vous vous réveillez pendant la nuit, parvenez-vous généralement à vous rendormir facilement ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_easily', 'label' => 'Très facilement, ou je me réveille rarement', 'points' => 1, 'applicable' => true),
                array('value' => 'easily', 'label' => 'Assez facilement', 'points' => 2, 'applicable' => true),
                array('value' => 'depends', 'label' => 'Cela dépend des nuits', 'points' => 3, 'applicable' => true),
                array('value' => 'difficult', 'label' => 'Difficilement', 'points' => 4, 'applicable' => true),
                array('value' => 'very_difficult', 'label' => 'Très difficilement ou pas du tout', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL06',
            'dimension' => 'regularite-rythme',
            'text' => 'Au cours des 14 derniers jours, vos heures habituelles de coucher et de lever ont-elles été relativement régulières ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_regular', 'label' => 'Très régulières', 'points' => 1, 'applicable' => true),
                array('value' => 'generally_regular', 'label' => 'Généralement régulières', 'points' => 2, 'applicable' => true),
                array('value' => 'variable', 'label' => 'Variables selon les jours', 'points' => 3, 'applicable' => true),
                array('value' => 'often_irregular', 'label' => 'Souvent irrégulières', 'points' => 4, 'applicable' => true),
                array('value' => 'very_irregular', 'label' => 'Très irrégulières', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL07',
            'dimension' => 'regularite-rythme',
            'text' => 'Entre vos jours de travail ou d\'études et vos jours libres, à quel point vos horaires de sommeil changent-ils généralement ?',
            'required' => true,
            'answers' => array(
                array('value' => 'very_little', 'label' => 'Très peu ou pas du tout', 'points' => 1, 'applicable' => true),
                array('value' => 'about_1h', 'label' => 'Environ 1 heure', 'points' => 2, 'applicable' => true),
                array('value' => '1h30_to_2h', 'label' => 'Entre 1 h 30 et 2 heures', 'points' => 3, 'applicable' => true),
                array('value' => '2h_to_3h', 'label' => 'Entre 2 et 3 heures', 'points' => 4, 'applicable' => true),
                array('value' => 'more_3h', 'label' => 'Plus de 3 heures', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL08',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous réveillé avec la sensation d\'avoir réellement récupéré ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_every_day', 'label' => 'Presque tous les jours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL09',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu du mal à rester éveillé ou attentif pendant la journée à cause de la somnolence ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => 'sometimes', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_every_day', 'label' => 'Presque tous les jours', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL10',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre sommeil vous a-t-il semblé suffisant pour maintenir une bonne énergie et une bonne concentration pendant la journée ?',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Jamais ou presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL11',
            'dimension' => 'habitudes-favorables-sommeil',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous consacré la période précédant votre coucher à des activités calmes favorisant la transition vers le sommeil ?',
            'help' => 'Exemples : réduction des activités stimulantes, routine calme, relaxation, arrêt du travail intense juste avant le coucher.',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_every_evening', 'label' => 'Presque tous les soirs', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'sometimes', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'never', 'label' => 'Jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL12',
            'dimension' => 'habitudes-favorables-sommeil',
            'text' => 'Au cours des 14 derniers jours, votre environnement et vos habitudes vous ont-ils généralement permis de dormir sans perturbations évitables ?',
            'help' => 'Il peut s\'agir de la lumière, du bruit, de la température, du téléphone, du travail dans le lit ou d\'autres facteurs modifiables.',
            'required' => true,
            'answers' => array(
                array('value' => 'almost_always', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => 'often', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => 'half_time', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => 'rarely', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => 'almost_never', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'duree-suffisance-sommeil',
            'label' => 'Durée et suffisance du sommeil',
            'question_ids' => array('SL01', 'SL02'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'endormissement-continuite',
            'label' => 'Endormissement et continuité',
            'question_ids' => array('SL03', 'SL04', 'SL05'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'regularite-rythme',
            'label' => 'Régularité du rythme',
            'question_ids' => array('SL06', 'SL07'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'recuperation-fonctionnement-diurne',
            'label' => 'Récupération et fonctionnement diurne',
            'question_ids' => array('SL08', 'SL09', 'SL10'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'habitudes-favorables-sommeil',
            'label' => 'Habitudes favorables au sommeil',
            'question_ids' => array('SL11', 'SL12'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'SATISFAISANT',
            'rank' => 0,
            'min' => 12,
            'max' => 24,
            'title' => 'Sommeil globalement satisfaisant',
            'description' => 'Votre sommeil est globalement satisfaisant. D\'après vos réponses, votre profil de sommeil apparaît globalement favorable dans plusieurs dimensions évaluées. Votre sommeil semble suffisamment long, relativement continu et régulier, avec une récupération globalement satisfaisante pendant la journée. Certaines dimensions peuvent néanmoins rester perfectibles. L\'objectif principal est de maintenir les habitudes favorables dans le temps et de préserver un bon équilibre entre durée, régularité, continuité du sommeil et récupération.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'ENCORE_FRAGILE',
            'rank' => 1,
            'min' => 25,
            'max' => 32,
            'title' => 'Sommeil encore fragile',
            'description' => 'La qualité de votre sommeil reste fragile. D\'après vos réponses, votre sommeil présente certains éléments favorables, mais plusieurs aspects semblent encore limiter sa qualité ou votre récupération. Votre durée de sommeil peut par exemple être correcte alors que votre rythme reste irrégulier, que les réveils nocturnes sont fréquents ou que votre récupération pendant la journée reste insuffisante. Votre profil se situe dans une zone intermédiaire : certaines bases sont favorables, mais des difficultés restent suffisamment présentes pour nécessiter une amélioration.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'PERTURBE',
            'rank' => 2,
            'min' => 33,
            'max' => 60,
            'title' => 'Sommeil perturbé',
            'description' => 'Votre sommeil semble actuellement perturbé. D\'après vos réponses, plusieurs dimensions de votre sommeil semblent actuellement défavorables. Votre résultat peut notamment refléter une durée de sommeil insuffisante, des difficultés d\'endormissement, des réveils nocturnes fréquents, des horaires irréguliers ou une récupération insuffisante pendant la journée. Ces difficultés peuvent également s\'accompagner d\'une baisse d\'énergie, de difficultés de concentration ou d\'une somnolence pendant la journée.',
            'recommendations' => array(),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'SLSF01',
            'text' => 'Vous a-t-on déjà signalé des pauses respiratoires, des étouffements ou des reprises de respiration inhabituelles pendant votre sommeil ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('SOMMEIL_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'unsure', 'label' => 'Je ne sais pas', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'SLSF02',
            'text' => 'Votre somnolence vous a-t-elle déjà mis en difficulté ou en danger, notamment au volant ou lors d\'une activité nécessitant de rester vigilant ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('SOMMEIL_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'SLSF03',
            'text' => 'Vos difficultés de sommeil persistent-elles depuis plusieurs semaines et affectent-elles fortement votre travail, vos études ou votre vie quotidienne ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('SOMMEIL_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
    ),
    'safety_messages' => array(
        'SOMMEIL_SAFETY_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses nécessitent une attention particulière.',
            'text' => 'Cette auto-évaluation ne permet pas d\'identifier la cause de ces signes. Il est recommandé d\'en parler à un professionnel de santé. Un bon score global ne doit jamais masquer un message d\'attention déclenché par une question de sécurité.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Le Score LifeMetrics - Sommeil est un outil propriétaire d\'auto-évaluation destiné à fournir un repère informatif sur les habitudes et le ressenti liés au sommeil. Il ne constitue pas un diagnostic médical et ne remplace pas l\'évaluation d\'un professionnel de santé.',
        'after' => 'Le score et les catégories ne constituent pas des seuils diagnostiques ou cliniques. Le questionnaire ne permet pas de diagnostiquer ou d\'exclure une insomnie, une apnée du sommeil, un trouble respiratoire du sommeil ou un autre trouble médical du sommeil. Il repose sur les réponses et le ressenti de l\'utilisateur concernant les 14 derniers jours. En cas de somnolence importante, de pauses respiratoires observées pendant le sommeil, de difficultés persistantes ou d\'un retentissement important sur la vie quotidienne, il est recommandé de demander conseil à un professionnel de santé. Les résultats du questionnaire ne doivent pas être utilisés pour déduire directement une mesure VitaScan ou une donnée corporelle.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => true,
        'technical_runtime' => true,
        'publication' => true,
    ),
);
