<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'sommeil',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Sommeil',
    'seo_title' => 'Auto-évaluation LifeMetrics - Quelle est la qualité de votre sommeil ?',
    'description' => 'Évaluer le profil global du sommeil : suffisance, continuité, régularité, récupération et retentissement diurne.',
    'population' => 'Adultes de 18 à 64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'SL01',
            'dimension' => 'duree-suffisance',
            'text' => 'Au cours des 14 derniers jours, combien de temps avez-vous dormi en moyenne par nuit ?',
            'help' => 'Il s\'agit du temps réellement dormi estimé, et non de l\'ensemble du temps passé au lit.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Moins de 5 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '5 h à moins de 6 h', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '6 h à moins de 7 h', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '7 h à 9 h', 'points' => 4, 'applicable' => true),
                array('value' => '4', 'label' => 'Plus de 9 h', 'points' => 3, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL02',
            'dimension' => 'duree-suffisance',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu l\'impression d\'avoir dormi suffisamment longtemps pour vos besoins ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL03',
            'dimension' => 'endormissement-continuite',
            'text' => 'Au cours des 14 derniers jours, combien de temps vous fallait-il généralement pour vous endormir après avoir décidé de dormir ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 60 minutes', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '46 à 60 minutes', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '31 à 45 minutes', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => '16 à 30 minutes', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => '15 minutes ou moins', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL04',
            'dimension' => 'endormissement-continuite',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre sommeil a-t-il été interrompu par des réveils qui vous ont réellement gêné ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque chaque nuit', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => '4-5 nuits par semaine', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => '2-3 nuits par semaine', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ 1 nuit par semaine', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement ou jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL05',
            'dimension' => 'endormissement-continuite',
            'text' => 'Lorsque vous vous réveillez pendant la nuit, parvenez-vous généralement à vous rendormir facilement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très difficilement ou pas du tout', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Difficilement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Cela dépend des nuits', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Assez facilement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très facilement, ou je me réveille rarement', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL06',
            'dimension' => 'regularite-rythme',
            'text' => 'Au cours des 14 derniers jours, vos heures habituelles de coucher et de lever ont-elles été relativement régulières ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très irrégulières', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent irrégulières', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Variables selon les jours', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Généralement régulières', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très régulières', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL07',
            'dimension' => 'regularite-rythme',
            'text' => 'Entre vos jours de travail ou d\'études et vos jours libres, à quel point vos horaires de sommeil changent-ils généralement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Plus de 3 heures', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Entre 2 et 3 heures', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Entre 1 h 30 et 2 heures', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ 1 heure', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très peu ou pas du tout', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL08',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous réveillé avec la sensation d\'avoir réellement récupéré ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque tous les jours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL09',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous eu du mal à rester éveillé ou attentif pendant la journée à cause de la somnolence ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque tous les jours', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL10',
            'dimension' => 'recuperation-fonctionnement-diurne',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence votre sommeil vous a-t-il semblé suffisant pour maintenir une bonne énergie et une bonne concentration pendant la journée ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais ou presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL11',
            'dimension' => 'habitudes-favorables',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous consacré la période précédant votre coucher à des activités calmes favorisant la transition vers le sommeil ?',
            'help' => 'Exemples : réduction des activités stimulantes, routine calme, relaxation, arrêt du travail intense juste avant le coucher.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque tous les soirs', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'SL12',
            'dimension' => 'habitudes-favorables',
            'text' => 'Au cours des 14 derniers jours, votre environnement et vos habitudes vous ont-ils généralement permis de dormir sans perturbations évitables ?',
            'help' => 'Il peut s\'agir de la lumière, du bruit, de la température, du téléphone, du travail dans le lit ou d\'autres facteurs modifiables.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'duree-suffisance',
            'label' => 'Durée et suffisance du sommeil',
            'question_ids' => array('SL01', 'SL02'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'endormissement-continuite',
            'label' => 'Endormissement et continuité',
            'question_ids' => array('SL03', 'SL04', 'SL05'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'regularite-rythme',
            'label' => 'Régularité du rythme',
            'question_ids' => array('SL06', 'SL07'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'recuperation-fonctionnement-diurne',
            'label' => 'Récupération et fonctionnement diurne',
            'question_ids' => array('SL08', 'SL09', 'SL10'),
            'weakest_eligible' => true,
        ),
        array(
            'id' => 'habitudes-favorables',
            'label' => 'Habitudes favorables au sommeil',
            'question_ids' => array('SL11', 'SL12'),
            'weakest_eligible' => true,
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'SOMMEIL_TRES_PERTURBE',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Sommeil très perturbé',
            'description' => 'Vos réponses indiquent que plusieurs dimensions de votre sommeil sont actuellement défavorables. Vous pouvez rencontrer une durée de sommeil insuffisante, des difficultés d\'endormissement, des réveils fréquents, un rythme irrégulier ou une récupération insuffisante pendant la journée.',
            'recommendations' => array(
                'Identifier les dimensions qui réduisent le plus votre score',
                'Essayer de stabiliser progressivement les horaires de sommeil',
                'Préserver une durée de sommeil suffisante',
                'Créer des conditions favorables à l\'endormissement',
                'Limiter les habitudes qui fragmentent ou retardent le sommeil',
            ),
        ),
        array(
            'code' => 'SOMMEIL_A_AMELIORER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Sommeil à améliorer',
            'description' => 'Votre sommeil présente certains éléments favorables, mais plusieurs aspects semblent encore limiter sa qualité ou votre récupération. Il peut être utile d\'identifier précisément les dimensions concernées : durée, endormissement, réveils nocturnes, régularité ou état au réveil.',
            'recommendations' => array(
                'Conserver les habitudes déjà favorables',
                'Améliorer en priorité vos deux dimensions les moins bien notées',
                'Maintenir des horaires plus réguliers',
                'Observer votre niveau d\'énergie et de somnolence pendant la journée',
            ),
        ),
        array(
            'code' => 'SOMMEIL_GLOBALEMENT_SATISFAISANT',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Sommeil globalement satisfaisant',
            'description' => 'Votre profil de sommeil apparaît globalement satisfaisant. Vous semblez bénéficier d\'une durée et d\'une qualité de sommeil relativement adaptées, même si certains éléments peuvent encore être optimisés.',
            'recommendations' => array(
                'Maintenir une durée de sommeil adaptée à vos besoins',
                'Conserver des horaires relativement réguliers',
                'Surveiller les périodes de fatigue ou de somnolence',
                'Protéger les habitudes qui facilitent votre récupération',
            ),
        ),
        array(
            'code' => 'SOMMEIL_FAVORABLE',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Sommeil favorable',
            'description' => 'Vos réponses décrivent actuellement des habitudes de sommeil globalement favorables. Votre sommeil semble suffisamment long, relativement continu et régulier, avec une récupération satisfaisante pendant la journée.',
            'recommendations' => array(
                'Maintenir ces habitudes dans le temps plutôt que chercher systématiquement à augmenter le score',
                'Préserver la régularité des horaires et les conditions favorables',
                'Rester attentif à tout changement durable de la qualité du sommeil',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(),
    'safety_questions' => array(
        array(
            'id' => 'SLSF01',
            'text' => 'Vous a-t-on déjà signalé des pauses respiratoires, des étouffements ou des reprises de respiration inhabituelles pendant votre sommeil ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'unknown', 'label' => 'Je ne sais pas', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HEALTH_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'SLSF02',
            'text' => 'Votre somnolence vous a-t-elle déjà mis en difficulté ou en danger, notamment au volant ou lors d\'une activité nécessitant de rester vigilant ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HEALTH_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'SLSF03',
            'text' => 'Vos difficultés de sommeil persistent-elles depuis plusieurs semaines et affectent-elles fortement votre travail, vos études ou votre vie quotidienne ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('HEALTH_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'HEALTH_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses méritent une attention particulière.',
            'text' => 'Cette auto-évaluation ne permet pas d\'identifier la cause de ces signes. Il est recommandé d\'en parler à un professionnel de santé.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir le bilan VitaScan',
            'url' => '/vitascan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre vos habitudes et votre ressenti concernant votre sommeil. Elle ne constitue pas un diagnostic médical et ne remplace pas l\'évaluation d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Sommeil est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories ont été conçus par LifeMetrics à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques. En cas de somnolence importante, de pauses respiratoires observées pendant le sommeil, de difficultés persistantes ou d\'un retentissement important sur votre vie quotidienne, demandez conseil à un professionnel de santé.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
