<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'pieds-confort-postural',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Pieds & confort postural',
    'seo_title' => 'Auto-évaluation LifeMetrics - Vos pieds influencent-ils votre confort au quotidien ?',
    'description' => 'Évaluer le confort des pieds et son retentissement sur la marche, la station debout, les activités quotidiennes et la stabilité ressentie',
    'population' => 'Adultes 18-64 ans',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'higher_is_better',
    'score' => array(
        'target_min' => 0,
        'target_max' => 48,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'PF01',
            'dimension' => 'douleur-inconfort',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous ressenti une douleur au niveau d\'un ou des deux pieds ?',
            'help' => 'Item symptomatique général, sans tentative d\'identifier la cause.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Tous les jours ou presque', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF02',
            'dimension' => 'douleur-inconfort',
            'text' => 'Lorsque vous ressentez une gêne au niveau des pieds, dans quelle mesure celle-ci perturbe-t-elle votre confort ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très fortement', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Fortement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Modérément', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Légèrement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Pas du tout ou presque pas', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF03',
            'dimension' => 'marche-station-debout',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous pu marcher aussi longtemps que vous le souhaitiez sans gêne importante au niveau des pieds ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF04',
            'dimension' => 'marche-station-debout',
            'text' => 'Lorsque vous restez debout pendant une période prolongée, comment vos pieds tolèrent-ils généralement cette situation ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très mal, je dois rapidement m\'asseoir ou changer d\'appui', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Mal', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Moyennement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Plutôt bien', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très bien', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF05',
            'dimension' => 'stabilite-appuis',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous senti stable et en confiance lorsque vous étiez debout ou en mouvement ?',
            'help' => 'Il s\'agit d\'une sensation de stabilité, pas d\'un test objectif d\'équilibre.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF06',
            'dimension' => 'stabilite-appuis',
            'text' => 'Au cours des 14 derniers jours, avez-vous eu l\'impression de charger davantage un pied, un côté du pied ou une jambe que l\'autre lorsque vous êtes debout ou marchez ?',
            'help' => 'Scoring inversé. La question porte sur un ressenti et n\'affirme pas l\'existence d\'une asymétrie biomécanique.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très souvent', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF07',
            'dimension' => 'chaussage-pressions',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vos chaussures habituelles vous ont-elles permis de marcher ou rester debout confortablement ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF08',
            'dimension' => 'chaussage-pressions',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous ressenti des zones de pression, de frottement ou d\'échauffement inhabituelles dans vos chaussures ?',
            'help' => 'Scoring inversé. On interroge une sensation directement perceptible par l\'utilisateur.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Tous les jours ou presque', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF09',
            'dimension' => 'retentissement-fonctionnel',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence une gêne au niveau des pieds vous a-t-elle conduit à réduire, reporter ou éviter une activité habituelle ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très souvent', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF10',
            'dimension' => 'retentissement-fonctionnel',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous modifié votre façon de marcher à cause d\'une douleur ou d\'un inconfort au niveau des pieds ?',
            'help' => 'Exemples : marcher plus lentement, raccourcir les pas, éviter certains appuis ou marcher davantage sur un côté.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très souvent', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Souvent', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Parfois', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Rarement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Jamais ou presque jamais', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF11',
            'dimension' => 'recuperation-confort-global',
            'text' => 'Après une journée avec beaucoup de marche ou de station debout, à quelle fréquence vos pieds retrouvent-ils un confort habituel après une période normale de repos ?',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Presque jamais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Rarement', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Environ la moitié du temps', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Souvent', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Presque toujours', 'points' => 4, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF12',
            'dimension' => 'recuperation-confort-global',
            'text' => 'En considérant globalement les 14 derniers jours, comment évalueriez-vous le confort de vos pieds dans votre vie quotidienne ?',
            'help' => 'Item intégratif final.',
            'required' => true,
            'answers' => array(
                array('value' => '0', 'label' => 'Très mauvais', 'points' => 0, 'applicable' => true),
                array('value' => '1', 'label' => 'Mauvais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Moyen', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Bon', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Très bon', 'points' => 4, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'douleur-inconfort',
            'label' => 'Douleur et inconfort des pieds',
            'question_ids' => array('PF01', 'PF02'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_DOULEUR_INCONFORT',
            ),
        ),
        array(
            'id' => 'marche-station-debout',
            'label' => 'Marche et station debout',
            'question_ids' => array('PF03', 'PF04'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_MARCHE_STATION_DEBOUT',
            ),
        ),
        array(
            'id' => 'stabilite-appuis',
            'label' => 'Stabilité et appuis ressentis',
            'question_ids' => array('PF05', 'PF06'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_STABILITE_APPUIS',
            ),
        ),
        array(
            'id' => 'chaussage-pressions',
            'label' => 'Chaussage et pressions',
            'question_ids' => array('PF07', 'PF08'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_CHAUSSAGE_PRESSIONS',
            ),
        ),
        array(
            'id' => 'retentissement-fonctionnel',
            'label' => 'Retentissement fonctionnel',
            'question_ids' => array('PF09', 'PF10'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_RETENTISSEMENT_FONCTIONNEL',
            ),
        ),
        array(
            'id' => 'recuperation-confort-global',
            'label' => 'Récupération et confort global',
            'question_ids' => array('PF11', 'PF12'),
            'weakest_eligible' => true,
            'attention' => array(
                'metric' => 'score',
                'operator' => '<=',
                'value' => 2,
                'message_code' => 'ATTENTION_RECUPERATION_CONFORT_GLOBAL',
            ),
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'INCONFORT_PODAL_IMPORTANT',
            'rank' => 0,
            'min' => 0,
            'max' => 15,
            'title' => 'Inconfort podal important',
            'description' => 'Vos réponses suggèrent que les douleurs ou gênes des pieds ont actuellement un retentissement important sur votre confort ou vos activités.',
            'recommendations' => array(
                'Marche',
                'Station debout',
                'Chaussage',
                'Stabilité ressentie',
                'Récupération',
                'Activités quotidiennes',
            ),
        ),
        array(
            'code' => 'CONFORT_PIEDS_A_AMELIORER',
            'rank' => 1,
            'min' => 16,
            'max' => 27,
            'title' => 'Confort des pieds à améliorer',
            'description' => 'Vous conservez certaines capacités fonctionnelles satisfaisantes, mais plusieurs dimensions montrent encore un inconfort ou une limitation.',
            'recommendations' => array(
                'Identifier les dimensions les plus faibles',
                'Prioriser les situations qui déclenchent ou aggravent la gêne',
                'Surveiller la persistance ou l\'aggravation des symptômes',
            ),
        ),
        array(
            'code' => 'CONFORT_GLOBALEMENT_FAVORABLE',
            'rank' => 2,
            'min' => 28,
            'max' => 38,
            'title' => 'Confort globalement favorable',
            'description' => 'Vos réponses décrivent un fonctionnement globalement satisfaisant des pieds au quotidien, avec éventuellement quelques situations spécifiques pouvant encore provoquer une gêne.',
            'recommendations' => array(
                'Maintenir les habitudes favorables',
                'Observer les dimensions plus faibles',
                'Tenir compte du chaussage et des situations de marche ou station debout prolongée',
            ),
        ),
        array(
            'code' => 'TRES_BON_CONFORT_PODAL',
            'rank' => 3,
            'min' => 39,
            'max' => 48,
            'title' => 'Très bon confort podal',
            'description' => 'Vos réponses indiquent actuellement un très bon niveau de confort des pieds dans les situations évaluées.',
            'recommendations' => array(
                'Maintenir les habitudes favorables',
                'Rester attentif à l\'apparition de nouvelles gênes ou limitations',
            ),
        ),
    ),
    'classification_rules' => array(),
    'classification_messages' => array(
        'ATTENTION_DOULEUR_INCONFORT' => array(
            'title' => 'Point nécessitant une attention particulière : Douleur et inconfort des pieds',
            'text' => 'Votre niveau de douleur ou d\'inconfort au niveau des pieds est particulièrement marqué.',
        ),
        'ATTENTION_MARCHE_STATION_DEBOUT' => array(
            'title' => 'Point nécessitant une attention particulière : Marche et station debout',
            'text' => 'La marche ou la station debout prolongée semble particulièrement difficile ou peu tolérée.',
        ),
        'ATTENTION_STABILITE_APPUIS' => array(
            'title' => 'Point nécessitant une attention particulière : Stabilité et appuis ressentis',
            'text' => 'Votre sensation de stabilité ou la symétrie de vos appuis ressentis présente une fragilité importante.',
        ),
        'ATTENTION_CHAUSSAGE_PRESSIONS' => array(
            'title' => 'Point nécessitant une attention particulière : Chaussage et pressions',
            'text' => 'Le confort dans vos chaussures ou la présence de zones de frottement et de pression est très contraignant.',
        ),
        'ATTENTION_RETENTISSEMENT_FONCTIONNEL' => array(
            'title' => 'Point nécessitant une attention particulière : Retentissement fonctionnel',
            'text' => 'La gêne au niveau des pieds entraîne une limitation ou une adaptation marquée de vos activités et de votre marche.',
        ),
        'ATTENTION_RECUPERATION_CONFORT_GLOBAL' => array(
            'title' => 'Point nécessitant une attention particulière : Récupération et confort global',
            'text' => 'La récupération après l\'effort ou votre confort global au quotidien reste particulièrement faible.',
        ),
    ),
    'safety_questions' => array(
        array(
            'id' => 'PFSF01',
            'text' => 'Avez-vous actuellement une plaie qui cicatrise mal, qui suinte ou une modification inhabituelle de la couleur ou de la température d\'un pied ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'PFSF02',
            'text' => 'Avez-vous récemment constaté une diminution ou une perte inhabituelle de sensibilité au niveau d\'un pied ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'PFSF03',
            'text' => 'Votre douleur est-elle apparue brutalement après une chute, un choc ou un autre traumatisme récent ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_ATTENTION_MESSAGE')),
            ),
        ),
        array(
            'id' => 'PFSF04',
            'text' => 'La douleur ou la gêne vous empêche-t-elle actuellement de marcher normalement ou d\'assurer vos activités habituelles ?',
            'required' => true,
            'answers' => array(
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_ATTENTION_MESSAGE')),
            ),
        ),
    ),
    'safety_messages' => array(
        'PIEDS_ATTENTION_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Certaines de vos réponses nécessitent une attention particulière.',
            'text' => 'Cette auto-évaluation ne permet pas d\'identifier l\'origine d\'une douleur ou d\'un trouble du pied. En présence d\'une douleur importante, d\'un traumatisme, d\'une perte de sensibilité, d\'une plaie ou d\'une modification inhabituelle du pied, demandez conseil à un professionnel de santé.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Découvrir mon bilan Podos360',
            'url' => '/podos360/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres tests',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => false,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Cette auto-évaluation LifeMetrics est destinée à vous aider à mieux comprendre le confort de vos pieds et leur retentissement éventuel sur vos activités quotidiennes. Elle ne permet pas de diagnostiquer une pathologie du pied, un trouble de la posture ou une anomalie biomécanique et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le Score LifeMetrics - Pieds & confort postural est un indicateur propriétaire d\'auto-évaluation. Son score et ses catégories sont conçus à des fins informatives et ne constituent pas des seuils diagnostiques ou cliniques.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => false,
        'technical_runtime' => true,
        'publication' => false,
    ),
);
