<?php

return array(
    'schema_version' => '2.0.0',
    'id' => 'pieds-confort-postural',
    'version' => '1.0.0',
    'status' => 'review',
    'locale' => 'fr-FR',
    'title' => 'Score LifeMetrics - Pieds & confort postural',
    'seo_title' => 'Auto-évaluation LifeMetrics - Vos pieds influencent-ils votre confort au quotidien ?',
    'description' => 'Le Score LifeMetrics - Pieds & confort postural est une auto-évaluation destinée à décrire le confort des pieds, les symptômes ressentis et leur retentissement éventuel sur la marche, la station debout et les activités quotidiennes.',
    'population' => 'Adultes',
    'recall_period' => '14 derniers jours',
    'estimated_duration' => '2-3 minutes',
    'scoring_direction' => 'lower_is_better',
    'score' => array(
        'target_min' => 12,
        'target_max' => 60,
        'normalize_when_unavailable' => false,
        'rounding' => 'half_up',
    ),
    'questions' => array(
        array(
            'id' => 'PF01',
            'dimension' => 'douleur-inconfort-pieds',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous ressenti une douleur au niveau d\'un ou des deux pieds ?',
            'help' => 'Item symptomatique général, sans tentative d\'identifier la cause.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Tous les jours ou presque', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF02',
            'dimension' => 'douleur-inconfort-pieds',
            'text' => 'Lorsque vous ressentez une gêne au niveau des pieds, dans quelle mesure celle-ci perturbe-t-elle votre confort ?',
            'help' => 'Échelle simple LifeMetrics ; aucune échelle clinique de douleur 0-10 n\'est utilisée.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Pas du tout ou presque pas', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Légèrement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Modérément', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Fortement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très fortement', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF03',
            'dimension' => 'marche-station-debout',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous pu marcher aussi longtemps que vous le souhaitiez sans gêne importante au niveau des pieds ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF04',
            'dimension' => 'marche-station-debout',
            'text' => 'Lorsque vous restez debout pendant une période prolongée, comment vos pieds tolèrent-ils généralement cette situation ?',
            'help' => 'Mesure uniquement le retentissement déclaré.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très bien', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Plutôt bien', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Moyennement', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Mal', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très mal, je dois rapidement m\'asseoir ou changer d\'appui', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF05',
            'dimension' => 'stabilite-appuis-ressentis',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vous êtes-vous senti stable et en confiance lorsque vous étiez debout ou en mouvement ?',
            'help' => 'Il s\'agit d\'une sensation de stabilité, pas d\'un test objectif d\'équilibre.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF06',
            'dimension' => 'stabilite-appuis-ressentis',
            'text' => 'Au cours des 14 derniers jours, avez-vous eu l\'impression de charger davantage un pied, un côté du pied ou une jambe que l\'autre lorsque vous êtes debout ou marchez ?',
            'help' => 'La question porte sur un ressenti et n\'affirme pas l\'existence d\'une asymétrie biomécanique.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très souvent', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF07',
            'dimension' => 'chaussage-pressions',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence vos chaussures habituelles vous ont-elles permis de marcher ou rester debout confortablement ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF08',
            'dimension' => 'chaussage-pressions',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous ressenti des zones de pression, de frottement ou d\'échauffement inhabituelles dans vos chaussures ?',
            'help' => 'On interroge une sensation directement perceptible par l\'utilisateur.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Tous les jours ou presque', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF09',
            'dimension' => 'retentissement-fonctionnel',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence une gêne au niveau des pieds vous a-t-elle conduit à réduire, reporter ou éviter une activité habituelle ?',
            'help' => 'Cette question fait partie de la dimension « Retentissement fonctionnel » et du guardrail fonctionnel.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très souvent', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF10',
            'dimension' => 'retentissement-fonctionnel',
            'text' => 'Au cours des 14 derniers jours, à quelle fréquence avez-vous modifié votre façon de marcher à cause d\'une douleur ou d\'un inconfort au niveau des pieds ?',
            'help' => 'Exemples : marcher plus lentement, raccourcir les pas, éviter certains appuis ou marcher davantage sur un côté. Cette question fait partie du guardrail fonctionnel.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Jamais ou presque jamais', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Rarement', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Parfois', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Souvent', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très souvent', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF11',
            'dimension' => 'recuperation-confort-global',
            'text' => 'Après une journée avec beaucoup de marche ou de station debout, à quelle fréquence vos pieds retrouvent-ils un confort habituel après une période normale de repos ?',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Presque toujours', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Souvent', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Environ la moitié du temps', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Rarement', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Presque jamais', 'points' => 5, 'applicable' => true),
            ),
        ),
        array(
            'id' => 'PF12',
            'dimension' => 'recuperation-confort-global',
            'text' => 'En considérant globalement les 14 derniers jours, comment évalueriez-vous le confort de vos pieds dans votre vie quotidienne ?',
            'help' => 'Item intégratif final.',
            'required' => true,
            'answers' => array(
                array('value' => '1', 'label' => 'Très bon', 'points' => 1, 'applicable' => true),
                array('value' => '2', 'label' => 'Bon', 'points' => 2, 'applicable' => true),
                array('value' => '3', 'label' => 'Moyen', 'points' => 3, 'applicable' => true),
                array('value' => '4', 'label' => 'Mauvais', 'points' => 4, 'applicable' => true),
                array('value' => '5', 'label' => 'Très mauvais', 'points' => 5, 'applicable' => true),
            ),
        ),
    ),
    'dimensions' => array(
        array(
            'id' => 'douleur-inconfort-pieds',
            'label' => 'Douleur et inconfort des pieds',
            'question_ids' => array('PF01', 'PF02'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'marche-station-debout',
            'label' => 'Marche et station debout',
            'question_ids' => array('PF03', 'PF04'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'stabilite-appuis-ressentis',
            'label' => 'Stabilité et appuis ressentis',
            'question_ids' => array('PF05', 'PF06'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'chaussage-pressions',
            'label' => 'Chaussage et pressions',
            'question_ids' => array('PF07', 'PF08'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'retentissement-fonctionnel',
            'label' => 'Retentissement fonctionnel',
            'question_ids' => array('PF09', 'PF10'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
        array(
            'id' => 'recuperation-confort-global',
            'label' => 'Récupération et confort global',
            'question_ids' => array('PF11', 'PF12'),
            'weakest_eligible' => true,
            'calculation_mode' => 'average',
        ),
    ),
    'weakest_dimensions' => array(
        'count' => 2,
        'tie_break' => 'configuration_order',
    ),
    'result_levels' => array(
        array(
            'code' => 'CONFORT_FAVORABLE',
            'rank' => 0,
            'min' => 12,
            'max' => 24,
            'title' => 'Confort des pieds globalement favorable',
            'description' => 'Votre confort des pieds est globalement favorable. D\'après vos réponses, vos pieds semblent globalement bien tolérer les situations évaluées au quotidien. La marche, la station debout, le chaussage et la récupération apparaissent généralement satisfaisants, avec peu de retentissement sur vos activités habituelles. Certaines situations peuvent néanmoins rester moins confortables ou provoquer ponctuellement une gêne. L\'objectif principal est de maintenir ce niveau de confort et de rester attentif à l\'apparition de nouvelles douleurs ou limitations.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'CONFORT_A_AMELIORER',
            'rank' => 1,
            'min' => 25,
            'max' => 32,
            'title' => 'Confort des pieds à améliorer',
            'description' => 'Le confort de vos pieds reste à améliorer. D\'après vos réponses, vous conservez certaines capacités fonctionnelles satisfaisantes, mais plusieurs dimensions montrent encore une gêne ou une limitation. Les difficultés peuvent apparaître pendant la marche, lors d\'une station debout prolongée, avec certaines chaussures, au niveau de la stabilité ressentie ou lors de la récupération après une journée sollicitant davantage les pieds. Votre profil se situe dans une zone intermédiaire : certaines situations sont bien tolérées, mais les difficultés restantes sont suffisamment présentes pour nécessiter une attention particulière.',
            'recommendations' => array(),
        ),
        array(
            'code' => 'INCONFORT_IMPORTANT',
            'rank' => 2,
            'min' => 33,
            'max' => 60,
            'title' => 'Inconfort podal important',
            'description' => 'Votre inconfort au niveau des pieds est actuellement important. D\'après vos réponses, les douleurs ou gênes au niveau des pieds semblent actuellement avoir un retentissement important sur votre confort ou vos activités quotidiennes. Votre résultat peut notamment refléter des douleurs fréquentes, une mauvaise tolérance de la marche ou de la station debout, des sensations de pression ou de frottement, une modification de votre façon de marcher, une récupération insuffisante ou des limitations dans certaines activités. Plusieurs dimensions contribuent donc actuellement à un profil de confort podal défavorable.',
            'recommendations' => array(),
        ),
    ),
    'classification_rules' => array(
        array(
            'id' => 'GUARDRAIL_PF09_LIMITATION',
            'type' => 'category_cap',
            'metric' => 'question_score',
            'question_id' => 'PF09',
            'operator' => '>=',
            'value' => 4,
            'max_category' => 'CONFORT_A_AMELIORER',
            'message_code' => 'PIEDS_GUARDRAIL_MESSAGE',
        ),
        array(
            'id' => 'GUARDRAIL_PF10_ADAPTATION',
            'type' => 'category_cap',
            'metric' => 'question_score',
            'question_id' => 'PF10',
            'operator' => '>=',
            'value' => 4,
            'max_category' => 'CONFORT_A_AMELIORER',
            'message_code' => 'PIEDS_GUARDRAIL_MESSAGE',
        ),
    ),
    'classification_messages' => array(
        'PIEDS_GUARDRAIL_MESSAGE' => array(
            'title' => 'Point d\'attention fonctionnel : limitation ou adaptation des activités',
            'text' => 'Votre score global reflète un niveau de confort favorable dans plusieurs dimensions. Cependant, vos réponses indiquent que la gêne au niveau des pieds limite fréquemment certaines activités ou vous conduit régulièrement à modifier votre façon de marcher. Ce retentissement fonctionnel doit être pris en compte même lorsque les autres dimensions sont favorables.',
        ),
    ),
    'safety_questions' => array(
        array(
            'id' => 'PFSF01',
            'text' => 'Avez-vous actuellement une plaie qui cicatrise mal, qui suinte ou une modification inhabituelle de la couleur ou de la température d\'un pied ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'PFSF02',
            'text' => 'Avez-vous récemment constaté une diminution ou une perte inhabituelle de sensibilité au niveau d\'un pied ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'PFSF03',
            'text' => 'Votre douleur est-elle apparue brutalement après une chute, un choc ou un autre traumatisme récent ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
        array(
            'id' => 'PFSF04',
            'text' => 'La douleur ou la gêne vous empêche-t-elle actuellement de marcher normalement ou d\'assurer vos activités habituelles ?',
            'required' => true,
            'answers' => array(
                array('value' => 'yes', 'label' => 'Oui', 'triggers' => array('PIEDS_SAFETY_MESSAGE')),
                array('value' => 'no', 'label' => 'Non', 'triggers' => array()),
            ),
        ),
    ),
    'safety_messages' => array(
        'PIEDS_SAFETY_MESSAGE' => array(
            'priority' => 100,
            'title' => 'Un point mérite votre attention.',
            'text' => 'Une douleur importante, un traumatisme, une perte de sensibilité, une plaie ou une modification inhabituelle du pied mérite un avis professionnel.',
        ),
    ),
    'result_ctas' => array(
        array(
            'label' => 'Je veux faire un bilan',
            'url' => 'https://lifemetrics.fr/formulaire-bilan/',
            'variant' => 'primary',
            'enabled' => true,
        ),
        array(
            'label' => 'Découvrir les autres questionnaires',
            'url' => '/tests-sante/',
            'variant' => 'secondary',
            'enabled' => true,
        ),
    ),
    'disclaimer' => array(
        'before' => 'Le Score LifeMetrics - Pieds & confort postural est un outil propriétaire d\'auto-évaluation destiné à fournir un repère informatif sur les symptômes ressentis au niveau des pieds et leur retentissement fonctionnel. Il ne permet pas de diagnostiquer une pathologie du pied, un trouble de la posture ou une anomalie biomécanique et ne remplace pas l\'avis d\'un professionnel de santé.',
        'after' => 'Le score et les catégories ne constituent pas des seuils diagnostiques ou cliniques. Le questionnaire repose sur le ressenti et les réponses déclarées par l\'utilisateur au cours des 14 derniers jours. Il ne mesure pas directement les appuis plantaires, l\'équilibre, la posture ou la biomécanique. Une sensation d\'instabilité ou d\'appui asymétrique déclarée dans le questionnaire ne permet pas de conclure à l\'existence d\'une anomalie biomécanique. L\'absence de symptômes déclarés ne garantit pas l\'absence d\'un trouble du pied ou d\'une anomalie biomécanique. En présence d\'une douleur importante ou persistante, d\'un traumatisme, d\'une plaie, d\'une perte de sensibilité ou d\'une limitation importante de la marche, un avis professionnel peut être nécessaire.',
    ),
    'approvals' => array(
        'content_scoring' => true,
        'legal_licensing' => true,
        'technical_runtime' => true,
        'publication' => true,
    ),
);

